### ISSUE TITLE
JSONResponseSerializer returns nil

### ISSUE THREAD

**Issue by SASDOE** [daltoniam/SwiftHTTP#100]
When printed as a string the output ressembles this : 
```
Optional({
  "events": [],
  "ocr_activity": "\u2018s'ziwyzt,\u2019  A",
  "ocr_token": "32;\u201c...",
  "status": "ko: No events found"
})
```

I have set the responseSerializer and am accessing the dict as such:
```
if let dict = response.responseObject as? Dictionary<String, AnyObject> { ... }
```

There are no errors reported in the console.

I am using the latest version as well. It used to work with 0.9.3, but I can't get it working since updating.

Here is a stripped down version for readability (so it might not compile but the idea is there) of the code in case you need it: http://dpaste.com/2PNHER3

**Comment by SASDOE** [comment]
I solved this using JSONJoy as per the server/client example. 

Thank you for these great libraries.

**Comment by SASDOE** [comment]
Not closing as this might be a bug after all, will let someone else decide.

**Comment by daltoniam** [comment]
I verified this with the latest code and the server/client example. It worked properly and as expected.
