### ISSUE TITLE
EXC_BAD_ACCESS in HTTPTask.swift

### ISSUE THREAD

**Issue by LeoUnglaub** [daltoniam/SwiftHTTP#102]
Hey,
i have now ported everything to the new completionHandler and since then my HTTP requests fail. In the `HTTPTask.swift` on line 478:

```swift
let blocks = self.backgroundTaskMap[session.configuration.identifier]
```
Any ideas why this is happening?
Greetings
Leo

**Comment by LeoUnglaub** [comment]
The request call itself looks like this:
```swift
self.httpRequest.POST ("/auth", parameters: self.httpPayload, completionHandler: {(response: HTTPResponse) in
	println (response.description)
})
```
or 
```swift
self.httpRequest.POST ("/auth", parameters: self.httpPayload, completionHandler: self.getAuthTokenCompletionHandler)
```

Thanks and greetings
Leo

**Comment by artakus** [comment]
Me too.
After update error occured.

**Comment by daltoniam** [comment]
I found an optional that wasn't being properly handled. Let me know if that resolves it.

**Comment by schnoddelbotz** [comment]
Hi,
For me, it also/still crashed. Debugger pointed at `session.configuration.identifier` being the culprit in `handleProgress()`. Adding a `if session.configuration.valueForKey("identifier") != nil { ...` in there is my current work-around to keep it from crashing ... anyway, may `session.configuration.identifier` be empty?

**Comment by mileswd** [comment]
Unfortunately it didn't fix it for me either, however @schnoddelbotz's solution worked.

**Comment by daltoniam** [comment]
I am having trouble reproducing this one. @schnoddelbotz interesting. Looking at the NSURLSession source, I didn't think the `identifier` property could be nil.

```swift
    /* identifier for the background session configuration */
    var identifier: String { get }
```

Does anyone have a url or request that will consistently reproduce this issue?

**Comment by mileswd** [comment]
@daltoniam 
>The value of this property is set only when you use the backgroundSessionConfigurationWithIdentifier: method to create the configuration object.

Most requests (`GET, POST, PATCH, PUT, HEAD, DELETE`) are created through `create(...)` which uses `NSURLSessionConfiguration.defaultSessionConfiguration()` as the `NSURLSession` configuration, therefore no identifier is set.

**Comment by daltoniam** [comment]
@mileswd nice find. Doesn't seem like the `identifier ` property should be a non optional then and should be optional since it can be nil. Swift doesn't want to check a variable it "knows" is not nil. I will file a bug on the radar and put in a temp fix. Thanks for the info.

**Comment by mileswd** [comment]
@daltoniam Thank you, much appreciated! :+1:

**Comment by daltoniam** [comment]
Radar issue: 21097168

**Comment by LeoUnglaub** [comment]
Thanks alot for the temporary fix!

**Comment by daltoniam** [comment]
welcome, thanks all for the feedback. Just released the `0.9.5` tag.

**Comment by mileswd** [comment]
Quick update: `NSURLSessionConfiguration.identifier` [has now been made optional](https://developer.apple.com/library/prerelease/mac/documentation/Foundation/Reference/NSURLSessionConfiguration_class/index.html#//apple_ref/occ/instp/NSURLSessionConfiguration/identifier).

**Comment by daltoniam** [comment]
Awesome! Glad to see that was done. Thanks for the update, I will probably roll it into a Swift 2.0/xCode 7 branch.
