### ISSUE TITLE
Missing argument for parameter 'failure' in call

### ISSUE THREAD

**Issue by jamorat** [daltoniam/SwiftHTTP#104]
![screen shot 2015-05-23 at 2 44 31 pm](https://cloud.githubusercontent.com/assets/5558998/7785364/98abf092-015a-11e5-80d1-5b59c113c608.jpg)
Inserted default get example, producing error

**Comment by daltoniam** [comment]
I assume you are using a tag (maybe through cocoaPods?). The current code in master hasn't gotten a tagged released, still looking at a few small things. I would either use the master branch code to get this working or look at the documentation in the `0.9.4` branch until `0.9.5` is created.

`0.9.4` docs if interested.
https://github.com/daltoniam/SwiftHTTP/tree/0.9.4

**Comment by jamorat** [comment]
Using Carthage... actually just putting in a failure tag helps. I will get a working example together.

**Comment by daltoniam** [comment]
ok cool. I don't do much with the different package manager, just try to provide support as requested. An example would be appreciated.

**Comment by jamorat** [comment]
Cool, I will do that this evening. Bear in mind that rather than an issue with Carthage, it's just an issue with the sample code in the readme of this project. By updating the sample code, all will be good. I will submit a pull request. Thanks again. I think we're good to close this issue if you'd like.
