### ISSUE TITLE
ssl pinning

### ISSUE THREAD

**Issue by giangqaz** [daltoniam/SwiftHTTP#108]
I try 
<code>
let path = NSBundle.mainBundle().pathForResource("jamjacert", ofType: "pem")
        var data :NSData = NSData(contentsOfFile: path!)!
        //println("data \(data.length)")
        request2.security = HTTPSecurity(certs: [HTTPSSLCert(data: data)], usePublicKeys: true)
</code>
but it not work.
I checked my key, it is loaded. or the way loading key is wrong?
I also tested that key by android apps.

**Comment by daltoniam** [comment]
If you are going to use a public key versus a certificate, you need to use the `HTTPSSLCert(key:)` method.

https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPSecurity.swift#L36

The `HTTPSSLCert(data:)` is designed for certificates
