### ISSUE TITLE
How to parse responseObject to json?

### ISSUE THREAD

**Issue by htarwara6245** [daltoniam/SwiftHTTP#109]
First of all,I really thank to the developer who created this such a beautiful and easy to use library

I am trying to parse responseObject to json to nsdictionary in my way not using Swift-Joy.Is there anyway that i can use my own json parsing library or custom?Here is my code
http://puu.sh/i9iyH/aacab41cf5.png
Any Help?

Thanks,now i am starting to use your library in swift 1.2.Really work great.But,i dont know what is ResponseObject actually mean?Is that NSData?

**Comment by htarwara6245** [comment]
Is there any way that i can use this perfect Library with SwiftyJSON?

**Comment by daltoniam** [comment]
Sure. Be something like:

```swift
var request = HTTPTask()
request.responseSerializer = JSONResponseSerializer()
request.GET("http://vluxe.io", parameters: nil, completionHandler: {(response: HTTPResponse) in
    if let err = response.error {
        println("error: \(err.localizedDescription)")
        return //also notify app of failure as needed
    }
  //pass the response.responseObject into swiftyJSON
   let json = JSON(data: response.responseObject)
   if let userName = json[0]["user"]["name"].string{
     //Now you got your value
   }
})
```

**Comment by htarwara6245** [comment]
Thanks Daltoniam,Thanks for such great library.With your help,I got fixed "Allow All Certificates" without doing or writing any complex code.And thank you for the answer.And there is one thing that i need to know.What is JSONResponseSerializer()?If the json return from server is inserted into LinkedHashMap,it will return NCSFDictionary in json?Am i right?is that what JSONResponseSerializer do?

Thank you,With Regards

**Comment by daltoniam** [comment]
It just simply passes in the `NSData` object from the NSURLSession response into the NSJSONSerialization parser.

https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPResponseSerializer.swift#L33

**Comment by htarwara6245** [comment]
I got it now,Thanks for the help...:)
