### ISSUE TITLE
unexpectedly found nil while unwrapping an Optional value error when web server is down

### ISSUE THREAD

**Issue by jdssem** [daltoniam/SwiftHTTP#110]
I got this error when I stopped my webserver. 
Xcode pointed code below in ```HTTPTask.swift``` when I got ```EXC_BAD_INSTRUCTION``` error because ```response``` was nil.

```
let resObj = resSerializer.responseObjectFromResponse(response, data: d)
```

How can I prevent this problem?

**Comment by codeleader** [comment]
Same error here. 
I fixed it by unwrapping `response` in `HTTPTask.swift` in `public func create(... `
```
if let resSerializer = self.responseSerializer, let resp = response {                     
   let resObj = resSerializer.responseObjectFromResponse(resp, data: d)                      
   serialResponse.responseObject = resObj.object
   serialResponse.error = resObj.error
}
```

**Comment by daltoniam** [comment]
Good catch and thanks for the fix. The change has been pushed to master.
