### ISSUE TITLE
SharedApplication() is unavailable (cocoapod 0.37.2)

### ISSUE THREAD

**Issue by Gabsao** [daltoniam/SwiftHTTP#113]
Hi,
I have an issue when I build my project i get this error : 

![capture d ecran 2015-06-07 a 22 23 57](https://cloud.githubusercontent.com/assets/12788043/8025833/f625843a-0d63-11e5-93ba-31be8b0cd75c.png)

I use the lastest cocopod 0.37.2 and the pod file look like this : 
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.2'
use_frameworks!

pod 'SwiftHTTP', '~> 0.9.5'
```
Thank you in advance

**Comment by daltoniam** [comment]
This isn't an issue with SwiftHTTP. I would check out this links for more info:

http://stackoverflow.com/questions/29288217/watchkit-sharedapplication-is-unavailable-not-available-on-ios-app-extensi
