### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by kadirarlii** [daltoniam/SwiftHTTP#116]
Can I get http cookie with this framework?
If I can, how?

**Comment by daltoniam** [comment]
I am not sure what you mean by "get an HTTP cookie". Cookies are just a header in HTTP, so you can pull them out threw that. You might be able to get them out of `NSHTTPCookieStorage` as well.

Header:
https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L32
