### ISSUE TITLE
NSURLSessionConfiguration upload error in iOS 7

### ISSUE THREAD

**Issue by fadion** [daltoniam/SwiftHTTP#118]
I'm building an app that is supposed to support iOS7+ and using SwiftHTTP for an image upload form. In iOS8 it works as it should, but in iOS7 I'm getting the following error:

`[NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:]: unrecognized selector sent to class`

`backgroundSessionConfigurationWithIdentifier` is iOS8 only, so I tried changing it to `backgroundSessionConfiguration(ident)`. This time, I'm getting the following error:

`Terminating app due to uncaught exception 'NSGenericException', reason: 'Upload tasks in background sessions must be from a file'`

Any easy fix for that?

**Comment by daltoniam** [comment]
Ah, I missed that API was iOS 8 only, my bad. Not sure about the upload task error. We spent some time with #98 figuring out uploads. I wonder if the older API only supported background file upload from a file and not from a streamed body.

**Comment by fadion** [comment]
Tried the code prior to #98, but `dataTaskWithRequest` doesn't support background tasks. Quite lost with this.

**Comment by daltoniam** [comment]
Yeah, the file upload background API in NSURLSession is very limited. It is only designed to work with a streaming body or a single file with no other parameters as far as I can tell. That usually doesn't work for my use cases (I usually have a file and an auth_token and a few other key/values). We changed it over the the streaming body which seem to resolve the issue for iOS8. I might suggest just using the `POST` (or whatever verb you are using for the upload) and background task.

https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

I know that is less than ideal, but can only work with the APIs we are given :confused:

**Comment by fadion** [comment]
I'll give `POST` a try and see where I get. Thanks a lot for your time.

**Comment by JaydeepPatel** [comment]
@daltoniam  hello, I am working in Objective C and o don't have more idea About NSURLSessionConfiguration , So i want to connet user Online Mode When I terminate the app. I m using XMPP server. So, Please Guide me Help me.
