### ISSUE TITLE
If i am going to test RequestTimeOut,how to set a timer?

### ISSUE THREAD

**Issue by htarwara6245** [daltoniam/SwiftHTTP#119]
Our country got the internet connection lower.So,I need to test my app about RequestTimeOut error.If i am going to make that request time in time,how do I set the timer?I tried to limit the bandwidth of my wifi.But,that error didn't got out from your library except the complete result

**Comment by daltoniam** [comment]
You can set a timeoutInterval via the requestSerializer. 

https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPRequestSerializer.swift#L39

```swift
var request = HTTPTask()
request.requestSerializer.timeoutInterval = 5
```

**Comment by htarwara6245** [comment]
Ohh yeah...Thanks for great support...Keep it up guys!!!!
