### ISSUE TITLE
When JSON Wrapped by Array

### ISSUE THREAD

**Issue by hyeonjae** [daltoniam/SwiftHTTP#120]
```json
[
  {
     "aa": 123
     "bb": 234
  }
]
```

Could I send a POST Request with this body ?

I want to send `[ [String:AnyObject] ]`. I need your help.
Thanks

**Comment by hyeonjae** [comment]
```swift
public func POST(url: String, parameters: Dictionary<String,AnyObject>?, completionHandler:((HTTPResponse) -> Void)!) {
    if let opt = self.create(url, method:.POST, parameters: parameters,completionHandler: completionHandler) {
        opt.start()
    }
}
```

**Comment by daltoniam** [comment]
Yeah it is setup right now to take a Dictionary for the requestSerializer as HTTP parameters are in key/value form and most JSON bodies I have seen are usually JSON objects. Changing it to take `AnyObject` would have some considerations as some of the serializer methods would have to change to support arrays as well. Pull Request is welcomed or if you have access to the API you could always change it to be something like `{"array": ["value1","value2"]}`

**Comment by daltoniam** [comment]
I rolled this into the Swift 2 update. Should be able to pass either dictionary or an array as the parameter. Thanks for the report, help improve the Swift 2 release.
