### ISSUE TITLE
invalid url

### ISSUE THREAD

**Issue by taug** [daltoniam/SwiftHTTP#121]
Download file with a url which contains Chinese will failed.The log is "invalid url".
Will some body fix this issue?

**Comment by daltoniam** [comment]
The only place that gets returned is here:

https://github.com/daltoniam/SwiftHTTP/blob/d5764984eb3fd1535a86ead9fcd44e9af376bea0/HTTPTask.swift#L390

It means NSURL wasn't able to create a valid URL off string passed in. You might want to look into if you can create a valid NSURL off your url string and see if it is issue there.

**Comment by taug** [comment]
Thanks.

**Comment by daltoniam** [comment]
See #123
