### ISSUE TITLE
Error "Cannot load underlying module for 'SwiftHTTP'

### ISSUE THREAD

**Issue by craigpearce5** [daltoniam/SwiftHTTP#125]
I followed the instructions for manual install but I get the error "Cannot load underlying module for 'SwiftHTTP' when I try to import the SwiftHTTP framework.

Any idea what could be causing this issue?

**Comment by daltoniam** [comment]
Well normally that means the framework is built or linked. Here is some pictures the build settings should look:
![screen shot 2015-06-20 at 1 55 07 pm](https://cloud.githubusercontent.com/assets/905059/8315213/d570e1e8-19a3-11e5-9cbf-794d1371aa17.png)

Also for reference:
![screen shot 2015-06-20 at 2 00 56 pm](https://cloud.githubusercontent.com/assets/905059/8315220/e5a93bdc-19a3-11e5-8786-b0bed0302f31.png)

Make sure if you are deploying to a real device (not the simulator) to follow this instructions as well:

https://github.com/daltoniam/SwiftHTTP#add-copy-frameworks-phase

**Comment by craigpearce5** [comment]
Ahh, I missed adding it to the target dependencies.  However, I see that is missing from instructions (unless I missed it somewhere else).

>Add the SwiftHTTP.xcodeproj to your Xcode project. Once that is complete, in your "Build Phases" add the SwiftHTTP.framework to your "Link Binary with Libraries" phase.
