### ISSUE TITLE
User set Content-Type

### ISSUE THREAD

**Issue by francisypl** [daltoniam/SwiftHTTP#126]
First off, thank you for making this - it is super helpful :smile: 

I am working on uploading to AWS S3 via a pre-signed url and I need to specify my own content type.

`let uploadObj = HTTPUpload(data: data!, fileName: media.url.lastPathComponent, mimeType: media.type.getMIMEType())`

however when I send the request the Content-Type is not what is specified.
The sever recieved this Content-Type
'multipart/form-data boundary=Boundary+17980097162831850979'

Any way I can specify the Content-Type of the request I make?

**Comment by daltoniam** [comment]
The file upload does a Multipart upload, is the API endpoint you are using expect a MultiPart upload?

**Comment by francisypl** [comment]
It has to be specific so match the SignedUrl signiture.
So if I request a key with a 'text/plain' content-type I have to send with a 'text/plain' content-type.

The content-type in SwiftHTTP has a weird 'Boundary+"%d` thing.
It would be a nice feature if the user can specify the content type :)

I just ended up using NSURLSession for this implementation.

**Comment by daltoniam** [comment]
ok cool. The weird boundary thing is apart of the HTTP multipart spec. If the S3 URL is expecting something different, then it makes sense why it didn't work. mutlipart is usually used for file uploads, but there are other ways to do it (if only one file is being uploaded).

http://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by francisypl** [comment]
thanks :)
