### ISSUE TITLE
Xcode 7 - Swift 2.0

### ISSUE THREAD

**Issue by mpclarkson** [daltoniam/SwiftHTTP#130]
I've forked this great library and I'm working on a basic swift 2.0 compatibility branch here https://github.com/mpclarkson/SwiftHTTP/tree/swift-2 

It's pretty rudimentary at the moment (e.g. no guards, throws etc) but once I have my project running in swift 2 and can test it properly I'll submit a pull request if you want?

**Comment by daltoniam** [comment]
Awesome, thanks! Yeah I haven't had time to start working on a Swift 2.0 branch yet, so a PR would be greatly appreciated. 

Also if you are interested, I setup a slack team to discuss the different OSS projects (SwiftHTTP, JSONJoy, Starscream, etc). Let me know if you would like an invite.

**Comment by mpclarkson** [comment]
That would be great my slack email is matt AT hilenium.com

**Comment by feiyun-li** [comment]
THX! This is really what I need

**Comment by mpclarkson** [comment]
@feiyun-li It seems to be working ok but let me know if you have any problems.

**Comment by feiyun-li** [comment]
Xcode 7 beta 4, a new syntax changes, I waited for this update

**Comment by anderoonies** [comment]
any news on a PR? thanks again @mpclarkson for doing this :pray:

**Comment by mpclarkson** [comment]
Ah, sorry I thought I'd already submitted a PR but hadn't. Just done so. I haven't had any time to work on it further as I've been working on backend stuff for the last month or so.

**Comment by codecowboy** [comment]
@mpclarkson is this PR merged now? Also, will this work for an OSX command line Tool or only iOS?

**Comment by acmacalister** [comment]
@codecowboy we aren't merging the swift 2 branches until Xcode 7/Swift 2 is out of beta. Until then, just use the swift 2 branch.

**Comment by codecowboy** [comment]
I tried with the swift 2 branch but get:
```
HTTPSecurity.swift:124:22: Cannot invoke 'SecPolicyCreateSSL' with an argument list of type '(Bool, String?)
```
Think I will just use NSURL :(

**Comment by SebastianOsinski** [comment]
@codecowboy Update Xcode 7 to the latest beta release. There was small change in the API - previously this initializer took Int and String? as arguments, in Xcode 7b5 it takes Bool and String?.

**Comment by mpclarkson** [comment]
Yep, update Xcode and it'll be fine. Can't wait for some stability!

**Comment by codecowboy** [comment]
Thanks all. I fudged a fix as I didn't want to update to XCode beta 5 just yet (I'm following a course which requires an earlier version)

```            policy = SecPolicyCreateSSL(1, domain as! CFString)```

**Comment by daltoniam** [comment]
For reference:

This will become the Swift 2 proper and is a big refactor for Swift 2. This will be merged into master.
https://github.com/daltoniam/SwiftHTTP/tree/swift-2

This is the backwards compatibility branch with minimal changes needed to support Swift 2.
https://github.com/daltoniam/SwiftHTTP/tree/swift-2-bc

Any questions let me know.

**Comment by UtkuDalmaz** [comment]
I am getting "Initialiser for conditional binding must have optional type not NSURL" error at
if let newPath = NSURL(fileURLWithPath: "\(path)/\(fileName)") {
When i try to download... (XCODE 7.1)

**Comment by JeffGos** [comment]
Any news on merging the swift2.0 branch into master?

**Comment by daltoniam** [comment]
Swift 2 branch has been merged into master!

**Comment by JeffGos** [comment]
Thanks. Could you update the podfile too please
