### ISSUE TITLE
https authentication not working?

### ISSUE THREAD

**Issue by digitaldesaster** [daltoniam/SwiftHTTP#132]
Hi, thanks for this tiny helper. great work.

i am using the code below and the connection to my rss-server on port 80 including the authentication is fine. 

but when i try to connect on port 443 i get "error: Access denied"

https://192.168.1.10:443/myservice

what can i do?

best regards
Alex

```swift
var request = HTTPTask()
//the auth closures will continually be called until a successful auth or rejection
var attempted = false
request.auth = {(challenge: NSURLAuthenticationChallenge) in
    if !attempted {
        attempted = true
        return NSURLCredential(user: "user", password: "passwd", persistence: .ForSession)
    }
    return nil //auth failed, nil causes the request to be properly cancelled.
}
request.GET("http://192.168.1.10/myservice", parameters: nil, completionHandler: {(response: HTTPResponse) in
    if let err = response.error {
        println("error: \(err.localizedDescription)")
        return //also notify app of failure as needed
    }
     println("winning!")
})
```

**Comment by daltoniam** [comment]
Glad to hear it is helping out! The url gets pass along to the NSURLSession APIs, nothing specific gets done for HTTPs connections. That error is probably coming from:

https://github.com/daltoniam/SwiftHTTP/blob/918153a19b2ad58830fe3d51791bb1d1fc3c1110/HTTPTask.swift#L424

Which means a 401 error is coming back. I might try putting a `println` inside the `request.auth` closure and make sure it is getting called for the HTTPS version as well. Let me know how it goes.

**Comment by daltoniam** [comment]
Where you able to test add see if the auth closure was getting called?

**Comment by digitaldesaster** [comment]
Hi, i will test it the next days. let you know..

**Comment by daltoniam** [comment]
Where you able to test it?

**Comment by digitaldesaster** [comment]
sorry dalton, still did not found the time .... :-( please close the ticket

**Comment by daltoniam** [comment]
I hear ya, never seems to be enough time :confused:. I am working on a full Swift 2 refactor, so maybe those changes will resolve it.
