### ISSUE TITLE
Support cancellation?

### ISSUE THREAD

**Issue by iori57** [daltoniam/SwiftHTTP#136]
This library is great! Is it possible to let user cancel the download process midway though?

Thanks!

**Comment by daltoniam** [comment]
Thanks, glad to hear it helps.

 The `create` method returns a `HTTPOperation` which is a subclass of `NSOperation`, thus it can be cancelled with the standard `cancel` method of `NSOperation`.

https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L142

```swift
var opt = request.create("http://vluxe.io", method: .GET, parameters: nil, completionHandler: {(response: HTTPResponse) in
//do stuff
 })
if let o = opt {
o.cancel() //cancel the request 
}
```

**Comment by iori57** [comment]
That's great, thanks again!!
