### ISSUE TITLE
When mobile user disable app setting: use cellular data, SwiftHTTP will crash

### ISSUE THREAD

**Issue by joeangel** [daltoniam/SwiftHTTP#137]
var request = HTTPTask()
request.GET
will occur app crash when user mobile user disable app setting: use cellular data.

**Comment by htarwara6245** [comment]
Can u provide us detail state?You mean you disable the "Use Cellular Data For" of your app in setting and when u run the app,the app crash at <code>request.GET</code> statement?
I see no error at <code>request.POST</code> of mine when internet connection is down or disabling the cellular data setting.So, if you describe any detail state about your problem,it will be really helpful to us.Thanks. Or share us your error at Stack.

**Comment by daltoniam** [comment]
@joeangel as @htarwara6245 said, could you please provide a bit more detail on how to reproduce this?

**Comment by joeangel** [comment]
Sure, I'll provide later.

**Comment by daltoniam** [comment]
@joeangel have you got a change to get those details?
