### ISSUE TITLE
USE GET Method , parameters : testEmptyArray=[] .

### ISSUE THREAD

**Issue by singi521** [daltoniam/SwiftHTTP#140]
USE GET Method , example: parameters : testEmptyArray=[] . <-- if empty array, never extend to collect , is bug?

print screen:
https://www.dropbox.com/s/kufkxw3dc54s8fg/%E8%9E%A2%E5%B9%95%E6%88%AA%E5%9C%96%202015-08-04%2023.33.19.jpg?dl=0

**Comment by daltoniam** [comment]
I tested this and it worked fine.
```swift
let task = HTTPTask()
task.GET("http://vluxe.io", parameters: ["array": []], completionHandler: { (response: HTTPResponse) in
    println("response is \(response.description)")
})
```
I am not sure how you are getting that error, can you share any sample code?

**Comment by singi521** [comment]
yes, it worked, but different with browser future.
test.php:
```php
if (empty($_GET['data'])){
	print_r("data is null");
}else{
	print_r("data len: ".count($_GET['data'])."<br>");
	for($i = 0; $i < count($_GET['data']); ++$i) {
		print_r("[$i]: ".$_GET['data'][$i]."<br>");
	}
}
```
Browser Test ： 
   request: [http://yafeeling.azurewebsites.net/test.php?data[]](http://yafeeling.azurewebsites.net/test.php?data[])
   response:
       **data len: 1
       [0]: **


SwiftHttp:
response : *data is null*
(should be： *data len: 1* right?)
```swift
func testGetRequest() {
        
        let request = HTTPTask()
        request.GET("http://yafeeling.azurewebsites.net/test.php", parameters: ["data":[]], completionHandler: {(response: HTTPResponse)  in
            if let err = response.error {
                println("Failure")
            }
            if let data = response.responseObject as? NSData {
                let str = NSString(data: data, encoding: NSUTF8StringEncoding)!
                println("str:\(str)") //output: data is null
            }
        })
        
    }
```

**Comment by daltoniam** [comment]
Ah I see. It doesn't send the empty array like you are expecting. It doesn't send the key as it doesn't have any values in it. I guess I could see how that might not be the desired behavior in some cases, but in others it makes sense, don't send a value you don't need. I will keep it in mind as I work on the Swift 2 changes.

**Comment by singi521** [comment]
thank you .
the project is good.
really appreciate it

**Comment by MykonBlu** [comment]
Can this be reopened? Unfortunately, some APIs have strict request parameters that may require an empty array. Rather than changing multiple APIs/putting in requests for them to change to remove keys which have no values (which I would ideally want!) - I think it may be a good idea to allow this in yours. 

Thumbs up on everything else though, I love it :)

**Comment by daltoniam** [comment]
yeah that is a fair point. I believe the best option would be a setting that is checked when serializing to do whichever is needed.

**Comment by daltoniam** [comment]
I add a way to do this in version 3.0.0 (just released). At the beginning of your app set: 
```swift
HTTPParameterProtocolSettings.sendEmptyArray = true
```
and an empty array will be sent along if the array value doesn't have anything in it.
