### ISSUE TITLE
How to import as a framework?

### ISSUE THREAD

**Issue by rushabhpasad** [daltoniam/SwiftHTTP#141]
On adding SwiftHTTP, as a sub-project, to my project, it's messing up the SVN repo. Rather, I would like to import this library as a framework and not as a sub-project.
I tried adding the SwiftHTTP.framework file to my project, but it's missing the necessary header files. Is there a better way to achieve this goal?

**Comment by acmacalister** [comment]
If you don't want to include the project in your Xcode workspace, you should be able to just build it as a standalone release version of the framework. You can do this by setting up the Xcode project to have a target to make a release version, but that isn't something we have looked into as it is a pretty rare configuration for OSS. If you just want to use the debug framework, just open the SwiftHTTP project build the framework, locate it in Finder and add to your project. It would only be a debug version of the framework, so if you wanted to have the optimizations of a release version you would need to go through the steps of setting up the target as mentioned above.
