### ISSUE TITLE
How to loop over JSON response if the response is a few levels deep

### ISSUE THREAD

**Issue by codecowboy** [daltoniam/SwiftHTTP#143]
```
var request = HTTPTask()
request.requestSerializer = JSONRequestSerializer()
request.responseSerializer = JSONResponseSerializer()
request.GET("https://truefire.com/api/site/courses/detail/732?show_videos=1&show_comments=0", parameters: nil, completionHandler: {(response: HTTPResponse) in
    if let err = response.error {
        print("error: \(err.localizedDescription)")
        
    }
    if let dict = response.responseObject as? Dictionary<String,AnyObject> {
        for (key, value) in dict {
            if key == "result" {
                print(value["videos"]) // this works and prints out all video objects
            }
        }
    }})
```
The videos property in the JSON contains a further level of video objects. How can I access the individual properties on each video object, preferably without resorting to using another library i.e JSONJoy-Swift

Apologies for the noobish question - it has taken me hours to get to this point via many cocoapods / command line tool related rabbit holes so any help much appreciated!

**Comment by SebastianOsinski** [comment]
I'm not sure if I understand your question correctly, but you probably can use `value["videos"].array` and then loop over it.

**Comment by codecowboy** [comment]
@SebastianOsinski thanks for the reply. Maybe this will help - link expires in an hour

http://pastebin.com/tfYnjvhX

I want to loop over all the videos and extract e.g. the title

**Comment by SebastianOsinski** [comment]
Sorry, I got confused, and my answer was valid if you would use SwiftyJSON. I spent couple of days working with SwiftHTTP and SwiftyJSON and somehow I mixed them. Sorry!

**Comment by codecowboy** [comment]
I sorted it with:
```
        for (key, value) in dict {
            if key == "result" {
                let videosArr = value["videos"] as! NSArray
                
                for vid in videosArr {
                    if let url = vid["videoFullURL"]! {
                        print (url)
                        //shell("/usr/local/bin/youtube-dl", "\(url)")
                    }
...
```
