### ISSUE TITLE
Status code 304 return 220

### ISSUE THREAD

**Issue by theewook** [daltoniam/SwiftHTTP#144]
Hi, 

I've got a RESTfull server and I'm trying to use ETag along with SwiftHTTP.
When my server returns a 304 (not modified) for some reason SwiftHTTP sees 200 as the status code.

I use httpResponse.description to display the information about the response.

Are you seeing the same thing on your side.

Cheers, Manuel

**Comment by theewook** [comment]
I am able to give you more details on this.This was due to the default cache policy (UseProtocolCachePolicy) set on the HTTPRequestSerializer

    public var cachePolicy: NSURLRequestCachePolicy = NSURLRequestCachePolicy. UseProtocolCachePolicy

Changing this to ReloadIgnoringLocalCacheData fix the issue.

**From HTTPTask.swift**

    if let code = serialResponse.statusCode where serialResponse.statusCode > 299 {
        serialResponse.error = self.createError(code)
    }

Also you are considering that if any status code greater than 299 is an error. Which is wrong (I think), it must be 399.

**Comment by daltoniam** [comment]
Alright good to know changing the cache fixed it. As far as the 299 status code is because NSURLSession automatically follows 300 redirects, so if you get a 301 back, that is probably not the expected behavior (too many redirects). I know it seems weird but makes sense with how the API works.
