### ISSUE TITLE
Having difficulties to deploy to iPhone 

### ISSUE THREAD

**Issue by sagarmakwana91** [daltoniam/SwiftHTTP#145]
It works awesome on simulator. But when i try to install build on my iPhone it gives me following error

dyld: Library not loaded: @rpath/SwiftHTTP.framework/SwiftHTTP
  Referenced from: /private/var/mobile/Containers/Bundle/Application/5B45A550-0FB0-4817-8AB0-7BBFAE3B559B/Infra Bank.app/Infra Bank
  Reason: image not found

I did all the steps mentioned in this issue.
https://github.com/daltoniam/SwiftHTTP/issues/37

Can you please help me ?

Thanks in Advance. :)

**Comment by acmacalister** [comment]
The only time I have seen that error is when the framework was not copied into your app's bundle on a real device, just like #37. Make sure you follow the steps in the ReadMe and double check to make sure the framework is getting copied over.

https://github.com/daltoniam/SwiftHTTP#add-copy-frameworks-phase
