### ISSUE TITLE
details on SSL pinning

### ISSUE THREAD

**Issue by tanimislam** [daltoniam/SwiftHTTP#146]
Hello, if possible could you clarify what types of data you accept for SSL certificate pinning in SwiftHTTP, in your README.md 
* for public keys, what format do you accept? Are these .cer/.crt files
* for certificates, what kind and format do you accept? For kind, do you accept the CA public certificate or the site's public certificate? What format do you accept: der or pem format, or both?
* An example where you document how to load a certificate or public key from an NSBundle, for SSL pinning, would be VERY VERY useful for us new developers.

**Comment by daltoniam** [comment]
- The public keys are either `SecKeyRef ` objects or they can be extracted from `cer` files.
- The only certificates I tested are using the `cer` files. 
- I will look into improving the docs with more examples the current one.
