### ISSUE TITLE
Archived submission failed with errors to appstore

### ISSUE THREAD

**Issue by aiqie** [daltoniam/SwiftHTTP#151]
Hi Dalton,

Am trying to submit my compiled application to appstore.
Am using XCode 6.3.2 to build and run my app.
I set already iOS deployment target to 7.1 for my app and SwiftHTTP.
Below is captured errors : 
I need guideline from you to solve this caused.

Thanks.

<img width="583" alt="screen shot 2015-09-08 at 1 43 19 pm" src="https://cloud.githubusercontent.com/assets/8154060/9728151/4e14ba0c-5630-11e5-91d3-b724ad1b0f90.png">
<img width="583" alt="screen shot 2015-09-08 at 1 43 04 pm" src="https://cloud.githubusercontent.com/assets/8154060/9728185/73d744bc-5630-11e5-9d95-4c05402f40b6.png">
<img width="584" alt="screen shot 2015-09-08 at 1 42 38 pm" src="https://cloud.githubusercontent.com/assets/8154060/9728207/9711ef90-5630-11e5-854c-7a59b96ecd17.png">
<img width="583" alt="screen shot 2015-09-08 at 1 42 14 pm" src="https://cloud.githubusercontent.com/assets/8154060/9728208/978d4c12-5630-11e5-8dfb-10c881d5a557.png">

**Comment by daltoniam** [comment]
Hi @aiqie. Since you are targeting iOS 7, you will need to copy the source in directly into your project. Embedded frameworks are only supported in iOS 8 and above.

**Comment by aiqie** [comment]
thank you @daltoniam..
now working like a charmed..
