### ISSUE TITLE
No network crash if use a response serializer 

### ISSUE THREAD

**Issue by akitoeki** [daltoniam/SwiftHTTP#152]
file: HTTPTask.swift
line: 219
```swift
if let resSerializer = self.responseSerializer {
                            let resObj = resSerializer.responseObjectFromResponse(response, data: d)
                            serialResponse.responseObject = resObj.object
                            serialResponse.error = resObj.error
                        }
```
if there's no internet connection then response is nil, thus making the call to responseObjectFromResponse crashed.

**Comment by daltoniam** [comment]
good point. Thanks for the report. I will fix that shortly.

**Comment by daltoniam** [comment]
What version of SwiftHTTP are you using? I see HTTPTask already having a fix for this bug:

https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L220

It is unwrapping response so it shouldn't be sending a nil response to the responseSerializer.

**Comment by akitoeki** [comment]
I'm on 0.9.4, through CocoaPods

**Comment by akitoeki** [comment]
you should update your readme to the latest version then to avoid confusion : ) will try to update to the latest version now

**Comment by daltoniam** [comment]
Yeah I probably should, I am bad about that :smile:. I will add a change log as apart of the Swift 2 changes.

**Comment by daltoniam** [comment]
Swift 1.2 branch now exist since 2.0 is now release.

https://github.com/daltoniam/SwiftHTTP/tree/swift-1.2

Also created a tag of `0.9.7` for CocoaPods to have final release of 1.2.
