### ISSUE TITLE
Dictionary parameter issue

### ISSUE THREAD

**Issue by pappzsolt100** [daltoniam/SwiftHTTP#155]
Hey,

I'm converting my code to swift 2.0 and I get the following error and can't find the solution:
//  let params = ["param": "param1", "array": ["first array element","second","third"], "num": 23, "dict": ["someKey": "someVal"]]
           
let params2 = ["token": activeUserToken, "email": ["to": email, "subject": subject, "message": message], "settings": settings, "lang": appSettings.activeLanguage]

let opt = try HTTP.POST(ServerConstants.BaseURL + urlEnd, parameters: params2)

 Cannot convert value of type 'NSDictionary' to expected argument type 'HTTPParameterProtocol?'

In the params2 dictionary every variable has String type and the settings is [String:String] dicitionary

If I use the params dictionary the post works fine

Thanks for the help!

**Comment by daltoniam** [comment]
The issue is the Swift compiler infers the wrong type with the mixed types. If you change `params2` to:
`let params2: Dictionary<String,AnyObject> = ...` It should work properly. I will updated the docs to include this. Thanks for the report.

**Comment by pappzsolt100** [comment]
Thanks for your answer! Now I'm using the the bc version, because of the narrow deadline, but later I'll try this.

**Comment by daltoniam** [comment]
:+1:
