### ISSUE TITLE
How to use ntlm with sharepoint

### ISSUE THREAD

**Issue by mubashirjavaid** [daltoniam/SwiftHTTP#157]
As I am trying to access Sharepoint 2013 REST api through this swifthttp. My sharepoint rest service is under SSL and using ntlm.
I provided URL and authentication by following code as under
```swift
do {
    let opt = try HTTP.GET("https://domain.com", parameters: nil)
    //the auth closures will continually be called until a successful auth or rejection
    var attempted = false
    opt.auth = { challenge in
        if !attempted {
            attempted = true
            return NSURLCredential(user: "user", password: "passwd", persistence: .ForSession)
        }
        return nil //auth failed, nil causes the request to be properly cancelled.
    }
    opt.start { response in
    //do stuff
    }
} catch let error {
    print("got an error creating the request: \(error)")
}
```
The point is that how we can get response here.

**Comment by mubashirjavaid** [comment]
Is there anyone who could help me

**Comment by daltoniam** [comment]
I forgot to add that to the new docs, will try to do that shortly. To get the response all you need to do is:
```swift
opt.start { response in
do {
let jsonData = try NSJSONSerialization.JSONObjectWithData(response.data, options: NSJSONReadingOptions())
} catch let error1 as NSError {
//do something with the error
}
}
```

**Comment by mubashirjavaid** [comment]
Still it's not working, Can we have discussion through skype of gtalk ?

**Comment by daltoniam** [comment]
No, I don't have time for something like that. You still haven't explained what you mean by you "can't get a response" or what the outcome of the example I provided above was other then it didn't work. I am happy to help, but please remember this is my free time I am donating to help out and I don't have any idea what your setup. I need concrete feedback to help troubleshoot the problem.
