### ISSUE TITLE
POST with data does not work with iOS 9

### ISSUE THREAD

**Issue by marcofiocco** [daltoniam/SwiftHTTP#159]
I used it with the previous version and it was fine. I have ported it to the new Upload class:
let opt = try HTTP.POST(URL, parameters: ["featuresfile": Upload(data: features, fileName: "featuresfile", mimeType: "application/octet-stream")])

and now it returns me with an internal server error (500).
Is the code wrong or there is something tricky with ATS settings?

a GET request works.

**Comment by daltoniam** [comment]
Thanks for the report. It was broken, but should be fixed now with the latest code. Thanks again.

**Comment by marcofiocco** [comment]
Thanks, but now I have other compile issues, for example it does not find these classes
    public var requestSerializer = HTTPRequestSerializer()
    public var responseSerializer: HTTPResponseSerializer?

**Comment by daltoniam** [comment]
Those classes do not exist anymore. The responseSerializer was removed as most JSON parsing libraries can parse raw NSData so it was a little bit redundant. The requestSerializer got add as an extension to `NSMutableURLRequest` (See the `Request.swift` for more info).
