### ISSUE TITLE
Pod install fails due to '1.0.0' not being tagged.

### ISSUE THREAD

**Issue by reidhoch** [daltoniam/SwiftHTTP#160]
rhochstedler$ pod --verbose spec lint

    SwiftHTTP (1.0.0) - Analyzing on iOS 8.0 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `SwiftHTTP` from `/Users/rhochstedler/Downloads/SwiftHTTP-master/SwiftHTTP.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A SwiftHTTP

Downloading dependencies

-> Installing SwiftHTTP (1.0.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/daltoniam/SwiftHTTP.git /var/folders/5q/wp5j186s6x36124j7w0qnxmm0000gn/T/d20150918-7821-yzjief --single-branch --depth 1 --branch 1.0.0
     Cloning into '/var/folders/5q/wp5j186s6x36124j7w0qnxmm0000gn/T/d20150918-7821-yzjief'...
     warning: Could not find remote branch 1.0.0 to clone.
     fatal: Remote branch 1.0.0 not found in upstream origin

[!] Error installing SwiftHTTP
 -> SwiftHTTP (1.0.0)
    - ERROR | [iOS] Encountered an unknown error ([!] /usr/bin/git clone https://github.com/daltoniam/SwiftHTTP.git /var/folders/5q/wp5j186s6x36124j7w0qnxmm0000gn/T/d20150918-7821-yzjief --single-branch --depth 1 --branch 1.0.0

Cloning into '/var/folders/5q/wp5j186s6x36124j7w0qnxmm0000gn/T/d20150918-7821-yzjief'...
warning: Could not find remote branch 1.0.0 to clone.
fatal: Remote branch 1.0.0 not found in upstream origin
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/spec/lint.rb:72:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by daltoniam** [comment]
I had not created the tag yet, was still finishing a few things up. Just pushed it up so it should be ready to go.
