### ISSUE TITLE
HTTP.POST, Swift 2, and JSONParameterSerializer()

### ISSUE THREAD

**Issue by cwoloszynski** [daltoniam/SwiftHTTP#161]
I am trying to post to a server using JSON for the parameters.  I used the older API and am now moving to the newer API.  

I am trying to get HTTP.POST(loginURL, parameters: parameters, requestSerializer: JSONParameterSerializer()) to compile. I get a 'JSONParameterSerializer' cannot be constructed because it has no accessible initializers

I don't see the issue in the code.  Thoughts on how to get this to work?

**Comment by daltoniam** [comment]
Thanks for the report, that was a bug. Forgot to add a the public `init` methods for the structs. Should be fixed now. Thanks!

**Comment by cwoloszynski** [comment]
Thanks!
