### ISSUE TITLE
README on SSL pinning might have typo

### ISSUE THREAD

**Issue by cwoloszynski** [daltoniam/SwiftHTTP#162]
In the Readme section on SSL pinning, the example code switches between opt and task.  I think it should use opt.security, not task.security

let opt = try HTTP.GET("https://domain.com", parameters: nil)
    task.security = HTTPSecurity(certs: [HTTPSSLCert(data: data)], usePublicKeys: true)
    //task.security = HTTPSecurity() //uses the .cer files in your app's bundle
    opt.start

**Comment by daltoniam** [comment]
Yep, that was bad typo/port. Fixed now. Thanks!

**Comment by cwoloszynski** [comment]
Thanks!  Great project.
