### ISSUE TITLE
Change var to let

### ISSUE THREAD

**Issue by LeoUnglaub** [daltoniam/SwiftHTTP#165]
Hey,
in the `swift-2-bc` branch you can change `HTTPTask.swift#422` from var to let because it is never mutated.

From 
```swift
var text: String = HTTPStatusCode(statusCode: code).statusDescription
```
to
```swift
let text: String = HTTPStatusCode(statusCode: code).statusDescription
```

Greetings
Leo

**Comment by daltoniam** [comment]
Easy enough. Thanks.

**Comment by LeoUnglaub** [comment]
Yeah, the hardest issue ever to report ;)
Thanks for fixing it ;)
