### ISSUE TITLE
There is no way to add custom header for request

### ISSUE THREAD

**Issue by Shiploop** [daltoniam/SwiftHTTP#167]
HTTP.GET("https://domain.com", parameters: ["hello": "there"], headers: ["header": "value"]) doesn't seem to exists

**Comment by daltoniam** [comment]
If you look at the code in the master branch you will see it is there:

https://github.com/daltoniam/SwiftHTTP/blob/master/Operation.swift#L282

I am assume you are using a package manager like cocoaPods which needed a new tag for this addition. I just pushed one, so try updating to the latest (`1.0.1`). I also added a CHANGELOG to keep everyone update to date when the latest releases go out.
