### ISSUE TITLE
Custom header example code does not compile

### ISSUE THREAD

**Issue by cwoloszynski** [daltoniam/SwiftHTTP#169]
I am looking to use custom headers (for Authorization Web Tokens, AWT) and your documentation shows setting them in the Operation constructor but the API does not support (as far as I can see).

Any idea how to do this under Swift2 APIs?

    let opt = HTTP.GET("https://domain.com", parameters: ["hello": "there"], headers: ["header": "value"])

**Comment by daltoniam** [comment]
Thanks for pointing that out. I forgot to put the `try` keyword in the example. That has been updated.

https://github.com/daltoniam/SwiftHTTP#custom-headers

**Comment by cwoloszynski** [comment]
Hmmm... I am trying to use the JSONParameterSerializer along with custom headers. I don't see how to use the new API (Swift2 refactoring) to use both.  I'm not even sure I see how the code supports the API you list above.  Am I missing something in the design?  

Thanks again for the great package!

**Comment by daltoniam** [comment]
I think you might be seeing it like the old API where the requestSerializer did the headers. That has change to be simpler and all you need to do is something like this:

```swift
let opt = try HTTP.GET("https://domain.com", parameters: ["hello": "there"], headers: ["header": "value"], requestSerializer: JSONParameterSerializer())
```

That should do a JSON parameter serialization and add the headers.

**Comment by eccsp** [comment]
Thanks!

On 2015-09-28 12:22 PM, Dalton wrote:
>
> I think you might be seeing it like the old API where the 
> requestSerializer did the headers. That has change to be simpler and 
> all you need to do is something like this:
>
> let  opt=  try  HTTP.GET("https://domain.com", parameters: ["hello":"there"], headers: ["header":"value"], requestSerializer: JSONParameterSerializer())
>
> That should do a JSON parameter serialization and add the headers.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/daltoniam/SwiftHTTP/issues/169#issuecomment-143795758>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
