### ISSUE TITLE
Missing argument for parameter 'method' in call

### ISSUE THREAD

**Issue by eccsp** [daltoniam/SwiftHTTP#170]
I'm trying to use the JSON Request Serializer snippet and getting this error. I have successfully used other examples but this one I just can it to work.

Is this a bug or I'm just missing something obvious?
Thanks in advance

![screen shot 2015-09-27 at 8 52 06 pm](https://cloud.githubusercontent.com/assets/11699613/10126140/a7f44b40-6559-11e5-94a1-7e3308fd1383.png)

**Comment by acmacalister** [comment]
ah, that is just a mistake in the README example, you need a `HTTPVerb` in the New call if you are not using the factory functions like `HTTP.GET` or `HTTP.POST`.

```swift
let operationQueue = NSOperationQueue()
operationQueue.maxConcurrentOperationCount = 2
do {
    let opt = try HTTP.New("https://google.com", method: .GET, parameters: nil)
    opt.onFinish = { response in
    //do stuff
    }
    operationQueue.addOperation(opt)
} catch let error {
    print("got an error creating the request: \(error)")
}
```

I will update the README with the fix shortly.
