### ISSUE TITLE
cannot send headers in POST request

### ISSUE THREAD

**Issue by reshadf** [daltoniam/SwiftHTTP#171]
Hello I try to do the following:

     func requestObjWithPost(url: Routes, params: Dictionary<String, String>?, customHeaders:  Dictionary<String, String>?, completionHandler: (response: Response?, error: NSError?) -> ())
     {
        self.requestConfig(completionHandler: { () -> () in
            
            do {
                let opt = try HTTP.POST(url.rawValue, parameters: params, headers: customHeaders) 
                opt.start { response in
                    if let err = response.error {
                        print("error: \(err.localizedDescription)")
                        return //also notify app of failure as needed
                    }
                    print("opt finished: \(response.description)")
                }
            } catch let error {
                print("got an error creating the request: \(error)")
            }
    }

But it gives me this error on the HTTP.POST:

** error is: Cannot invoke 'POST' with an argument list of type '(String, parameters: Dictionary<String, String>?, headers: Dictionary<String, String>?)'

while according the docs I can give custom header with it. How can I modify this to pass optional headers without having this error?

**Comment by daltoniam** [comment]
I just tried your code and it built fine. Are you sure you are using the latest `1.0.1` version?
