### ISSUE TITLE
Crash at app start

### ISSUE THREAD

**Issue by delphswiftier** [daltoniam/SwiftHTTP#174]
dyld: Library not loaded: @rpath/SwiftHTTP.framework/SwiftHTTP
  Referenced from: /var/mobile/Containers/Bundle/Application/90F6C42F-64BD-46F4-8C8D-F0A9EE5F2048/VkMusic(!!).app/VkMusic(!!)
  Reason: image not found
(lldb) 
<img width="374" alt="2015-10-03 15 41 22" src="https://cloud.githubusercontent.com/assets/14165455/10262931/39d46006-69e5-11e5-973a-4ecca8098392.png">

**Comment by acmacalister** [comment]
When building on a real device you need to make sure you copy the framework into the app bundle as outlined in the README.

https://github.com/daltoniam/SwiftHTTP#add-copy-frameworks-phase
