### ISSUE TITLE
request.GET dont enter in the completionHandler

### ISSUE THREAD

**Issue by Persilos** [daltoniam/SwiftHTTP#175]
Hi,
I have a problem after updated SwiftHTTP to Swift 2 with GET method.
GET doesnt enter in the completionHandler, it directly go out... And my URL parameter is OK.
<img width="782" alt="capture d ecran 2015-10-05 a 16 19 11" src="https://cloud.githubusercontent.com/assets/8830732/10282729/94bb16a2-6b7c-11e5-98cb-fd0efbc876da.png">

It's directly jump out... So i cant treat my data (before the update, my app's worked perfectly...)
Can you help me ?

**Comment by daltoniam** [comment]
Well it looks like you are using the backward compatibility branch and that had minimal changes. I believe other folk have used it with success. Do you mean the completionHandler isn't running? The responseObject is nil?

**Comment by Persilos** [comment]
It's ok, i just add 
<key>NSAppTransportSecurity</key>
<dict>
  
  <key>NSAllowsArbitraryLoads</key>
      <true/>
</dict>

in my info.plist

My error was "Transport security has blocked a cleartext HTTP (http://) resource load since it is insecure. "
Dont see it, cause i fixed it previously... I dont know why my info.plist get reset :D 

Ty for your help
