### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by mdsinghmalik** [daltoniam/SwiftHTTP#176]
Hey Daltoniam,

Love your work and thanks for giving us a quick 2.0 update. :+1:  :+1: 

I was wondering if there is away to get the progress for upload & download. 

Thanks

**Comment by acmacalister** [comment]
We haven't added the progress closure back in the Swift 2 refactor. It is on the TODO list. Hopefully we can get to it this week.

**Comment by daltoniam** [comment]
I added the progress closure. See https://github.com/daltoniam/SwiftHTTP#progress

**Comment by daltoniam** [comment]
Tag `1.0.2` released.

**Comment by gtona** [comment]
Hi @daltoniam I tried opt.progress but I always get 0.0 progress until the upload is completely finished. Has anyone else experienced this?

**Comment by daltoniam** [comment]
@gtona are you uploading a file using `Upload`? We aren't specifically using a `NSURLSessionUploadTask` so that delegate might not be getting called for uploads by the standard task. We might need to add a way to use an upload task to get this functionality.

https://developer.apple.com/library/watchos/documentation/Foundation/Reference/NSURLSessionUploadTask_class/index.html

**Comment by gtona** [comment]
@daltoniam I am not using upload. I am using SwiftHttp's post method like so:
```
do {
            let opt = try HTTP.POST("someDomain", parameters: ["someParameters"], headers: ["someHeaders"])
            opt.progress = { progress in
                print("progress: \(progress)") //this should be between 0 and 1.
            }
            opt.start { response in
                if let err = response.error {
                    print("error: \(err.localizedDescription)")
                    return 
                }
                if let data:NSData = response.data {
                    let str = NSString(data: data, encoding: NSUTF8StringEncoding)
                    print("response: \(str!)") 
                    success(data)
                }
            }
        } catch let error {
            print("got an error creating the request: \(error)")
        }
```

**Comment by daltoniam** [comment]
Alright, so what progress are you expecting to see? The progress of the parameters being POST'ed or the progress of downloading the response?
