### ISSUE TITLE
Where to set the timeout interval

### ISSUE THREAD

**Issue by S4TNEW** [daltoniam/SwiftHTTP#177]
Hi, in the Swift 2.0 version I wasn't able to find where to set the timeout interval of the request.

Former variant: `request.requestSerializer.timeoutInterval`

Is there a posibility or do I have to settle with the compatibility branch?

**Comment by acmacalister** [comment]
SwiftHTTP uses protocol extensions now, so you have direct access to the `NSMutableURLRequest` You should set your `timeoutInterval` there.

https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSMutableURLRequest_Class/#//apple_ref/occ/instp/NSMutableURLRequest/timeoutInterval

So here would be an example:

```swift
if let req = NSMutableURLRequest(urlString: "http://domain.com") {
    do {
        try req.appendParameters(["hello": "there"])
        req.addValue("custom", forHTTPHeaderField: "header")
        req.timeoutInterval = 10 // here we set the timeout!
        let opt = HTTP(req)
        opt.start { response in
            //do stuff
        }
    } catch let error {
        print("couldn't serialize the paraemeters: \(error)")
    }
}
```
