### ISSUE TITLE
Trying to set the timeout when using the HTTP.GET and HTTP.POST methods

### ISSUE THREAD

**Issue by cwoloszynski** [daltoniam/SwiftHTTP#179]
I am trying to determine how to set the timeoutInterval using the HTTP.GET and HTTP.POST methods in the Swift2 APIs.  

It looks like (from looking at other issues on GitHub) that you are suggesting that users recreate the functionality of HTTP.New().  

Can I suggest that the verb-based APIs be extended to include a timeout value as an option?  Or, perhaps a class-based default value to use to set this value?

Is this something you'd consider supporting?

**Comment by daltoniam** [comment]
I can see how the might be a benefit, but I believe I came up with a solution that won't require me to forward on every property of `NSMutableURLRequest` and still gives the behavior desired. Check out:

https://github.com/daltoniam/SwiftHTTP#global-handlers

**Comment by daltoniam** [comment]
Tag `1.0.2` released.

**Comment by cwoloszynski** [comment]
This looks great and thank you for making this happen.  I am in the midst of re-working my code from ABAddressBook to CNContact and I'm slogging through that process.  Once I get to the other side, I will check this out and move over to this approach.  Looks great!
