### ISSUE TITLE
Trying to post array dictionaries result {}

### ISSUE THREAD

**Issue by onsterion** [daltoniam/SwiftHTTP#180]
Hi,

Im Trying to post  a array dictionaries but the result in server header is {}

Example:

var listData : [[String:Any]] = [
                [
                    "ID": "5002",
                    "Accuracy": 25,
                    "Time": "123456"
                ]
            ]

do {
                let opt = try HTTP.POST(url, parameters: listData )
                opt.start { response in
                    print("Data Send: \(response)")
                }
            } catch let error {
                print("got an error creating the request: \(error)")
            }

**Comment by onsterion** [comment]
I change [[String:Any]] for [Dictionary<String,AnyObject>]

The result in xcode is:

[[:], ["iBeaconID": 5005, "iBeaconAccuracy": 0.397, "iBeaconTime": 2015-10-14 17:30:26 +0000], ["iBeaconID": 5004, "iBeaconAccuracy": 0.405, "iBeaconTime": 2015-10-14 17:30:28 +0000], ["iBeaconID": 5003, "iBeaconAccuracy": 0.8090000000000001, "iBeaconTime": 2015-10-14 17:30:29 +0000], ["iBeaconID": 5002, "iBeaconAccuracy": 7.742, "iBeaconTime": 2015-10-14 17:30:23 +0000]]

But the result in server is:

[ [ 'iBeaconID', [ '5005', '5004', '5003', '5002' ] ],
[ 'iBeaconAccuracy',
    [ '0.397', '0.405', '0.8090000000000001', '7.742' ] ],
  [ 'iBeaconTime',
    [ '2015-10-14 17:30:26 +0000',
      '2015-10-14 17:30:28 +0000',
      '2015-10-14 17:30:29 +0000',
      '2015-10-14 17:30:23 +0000' ] ] ]

**Comment by vbrazo** [comment]
+1

**Comment by vbrazo** [comment]
I have the same problem here.

I am trying to post: ```let opt = try HTTP.GET(url, parameters: ["email": self.txtEmail.text])```

but when I check the value of my email params in the server, it always returns nil.

**Comment by daltoniam** [comment]
I just tested this and it worked fine. Both the HTTP headers and parameters should up properly. Just to be clear, parameters` are form value or url value parameters and `headers`are the HTTP headers.
