### ISSUE TITLE
Content-Type

### ISSUE THREAD

**Issue by alaindixon** [daltoniam/SwiftHTTP#181]
Hi,
First of all, thank you for your library.
I've tried to POST data on the server side but I got nothing (I did received the request without data form).
I've check the header with CHARLES software and I don't know why but the Content-Type is wrong.
It's text/html instead of application/x-www-form-urlencoded
I've tried to force the header Content-Type but it's does not work :(

 let params = ["data": ["id": 1, "name": "Maison"]]
        
        do {
            let opt = try HTTP.POST("http://test1.adixon.fr/webservice-save-flat", parameters: params)                        
            opt.start { response in
            print("opt finished: \(response.description)")
            }
        } catch let error {
            print("got an error creating the request: \(error)")
        }

Any idea ?

**Comment by daltoniam** [comment]
What version/tag of SwiftHTTP are you running? I just tried it with the latest code from master against a test go server and the content-type was set correctly.
```swift
do {
    let opt = try HTTP.POST("http://localhost:8080/bar", parameters: ["hello": "there"])
    opt.start { response in
    //do stuff
    }
} catch let error {
    print("got an error creating the request: \(error)")
}
```
Server code:
```go
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/bar", func(w http.ResponseWriter, r *http.Request) {
		log.Println("got a web request")
		fmt.Println("header: ", r.Header.Get("Content-Type"))
		vals := r.URL.Query()
		if len(vals) == 0 {
			r.ParseMultipartForm(1024 * 1024)
			vals = r.Form
		}
		for k, v := range vals {
			fmt.Println("key:", k)
			fmt.Println("value:", v)
		}
		w.Write([]byte("{\"status\": \"ok\"}"))
	})

	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

The server output was:
```
2015/10/17 17:53:56 got a web request
header:  application/x-www-form-urlencoded; charset=utf-8
key: hello
value: [there]
```

**Comment by alaindixon** [comment]
Sorry, my mistake, apparently the header is good:
Should be an error on the server side, I don't know what exactly.

POST /webservice-save-flat HTTP/1.1
Host	test1.adixon.fr
Content-Type	application/x-www-form-urlencoded; charset=utf-8
Connection	keep-alive
Accept	*/*
User-Agent	Horizon360/1 CFNetwork/758.0.2 Darwin/14.4.0
Content-Length	36
Accept-Language	en-us
Accept-Encoding	gzip, deflate

**Comment by alaindixon** [comment]
I took the lastest version, it's seems to work now, I did install your library with pod.
