### ISSUE TITLE
Not sure about the installation procedure...

### ISSUE THREAD

**Issue by arnaudlamy** [daltoniam/SwiftHTTP#183]
I created a new Xcode 7 project in swift. I quit then Xcode, and create the pod file.

pod init
Then I edited the file with the configuration provided:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SwiftHTTP', '~> 1.0.0'
Then:

$ pod install              

Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using SwiftHTTP (1.0.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
I reopened my Xcode project and added import SwiftHTTP but the build failed with this error : No such module 'SwiftHTTP'

I rechecked the documentation but that's all I have, I did missed something but I don't know what it is !

Thanks.

**Comment by barrettclark** [comment]
I just threw together a scratch project using `SwiftHTTP` and a few other libraries that I like.  Here is my Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'  
platform :ios, '9.0'
use_frameworks!

pod 'Argo'
pod 'Curry'
pod 'BrightFutures'
pod 'SwiftHTTP', '~> 1.0.0'
```

Running `pod install` worked fine for me.  I just installed Xcode 7.1 today, and also just installed CocoaPods.  I was really hoping to be able to ditch CocoaPods and just use Carthage, but BrightFutures doesn't play nice with Carthage right now.  Carthage doesn't really play nice with Xcode right now either for that matter.

**Comment by arnaudlamy** [comment]
Thanks for your return ! 

I was still using the project file that's why I've got the issue. Now I have another on when I import the library which is: `Cannot load underlying module for 'SwiftHTTP'`

I just pod install with success opened the xcworkspace file and add ìmport SwiftHTTP` in my ViewController file.

Any idea what I missed ?

**Comment by arnaudlamy** [comment]
In fact nothing, it was a bug in Xcode 7.0. Works fine with XCode 7.1 thanks !

**Comment by barrettclark** [comment]
You bet! I'm glad you were able to get squared away. :shipit:

**Comment by daltoniam** [comment]
@barrettclark thanks!
