### ISSUE TITLE
How to I know the completion of NSOperationQueue?

### ISSUE THREAD

**Issue by yoneapp** [daltoniam/SwiftHTTP#185]
I thought such a code.

```swift
let operationQueue = NSOperationQueue()
operationQueue.suspended = true
operationQueue.maxConcurrentOperationCount = 5
do {
    let opt = try HTTP.New("https://www.example.com/", method: .GET)
    opt.onFinish = { response in
        print("onFinish-1")
        sleep(10)
        print("onFinish-2")
    }
    operationQueue.addOperation(opt)
} catch let error {
    print("got an error creating the request: \(error)")
}

operationQueue.suspended = false

dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
    operationQueue.waitUntilAllOperationsAreFinished()
    print("UntilAllOperationsAreFinished")
}
```

The result is this.

```
onFinish-1
UntilAllOperationsAreFinished
onFinish-2
```

I hope this.

```
onFinish-1
onFinish-2
UntilAllOperationsAreFinished
```

Can I have your input on this?

**Comment by reshadf** [comment]
Try using completion handler to wait for your requests to finish.

**Comment by yoneapp** [comment]
Thanks. It went well.

```
let operationQueue = NSOperationQueue()
operationQueue.suspended = true
operationQueue.maxConcurrentOperationCount = 5

let semaphore = dispatch_semaphore_create(0)

do {
    let opt = try HTTP.New("https://www.example.com/", method: .GET)
    opt.onFinish = { response in
        print("onFinish-1")
        sleep(1)
        print("onFinish-2")
        dispatch_semaphore_signal(semaphore)
    }
    operationQueue.addOperation(opt)
} catch let error {
    print("got an error creating the request: \(error)")
}

dispatch_async(dispatch_queue_create("com.example", nil)) {
    dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
    print("UntilAllOperationsAreFinished")
}

operationQueue.suspended = false
```

**Comment by yoneapp** [comment]
In this case, It will work as expected.
What is the difference between addOperationWithBlock and onFinish?
I think It is better to have the same operation.

```swift
let operationQueue = NSOperationQueue()
operationQueue.maxConcurrentOperationCount = 5

operationQueue.addOperationWithBlock {
    print("block-1")
    sleep(5)
    print("block-2")
}

dispatch_async(dispatch_queue_create("com.example", nil)) {
    operationQueue.waitUntilAllOperationsAreFinished()
    print("UntilAllOperationsAreFinished")
}
```

**Comment by daltoniam** [comment]
`OnFinish` is for when the HTTP request finishes (and thus the operation). The `OnFinish` isn't apart of the overall operation, so the sleep would not work (and HTTP requests can't be suspended).   `addOperationWithBlock ` executes that closure and sees the operation as being finished once the closure/block finishes.

**Comment by yoneapp** [comment]
I understand. Thank you for your advice.

**Comment by nitisha1** [comment]
This is my code 
   
       for i in 1...5
       {
        let semaphore = dispatch_semaphore_create(0)
        queue.addOperationWithBlock({
          
            Downloader.downloadImageWithURL(imageURLs[3])
            NSOperationQueue.mainQueue().addOperationWithBlock({
                 dispatch_semaphore_signal(semaphore)
               
                print(i)
            })
        
        })
        dispatch_async(dispatch_queue_create("com.example", nil)) {
            dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
            print("UntilAllOperationsAreFinished")
        }
        sleep(2)
        }

expected output 
1
UntilAllOperationsAreFinished
2
UntilAllOperationsAreFinished
3
UntilAllOperationsAreFinished
4
UntilAllOperationsAreFinished
5
UntilAllOperationsAreFinished
///////////

Result prints
1
UntilAllOperationsAreFinished
2
UntilAllOperationsAreFinished
3
UntilAllOperationsAreFinished
5
UntilAllOperationsAreFinished
4
UntilAllOperationsAreFinished
