### ISSUE TITLE
Redo a request.

### ISSUE THREAD

**Issue by reshadf** [daltoniam/SwiftHTTP#186]
Hello, right now I have a base wrapper method to handle all my requests. 

    func requestObj(ReqMethod: HTTPVerb, url: Route, params: Dictionary<String, AnyObject>?, completionHandler: (response: Response?, error: NSError?) -> ())
    {
        do {
            let opt = try HTTP.New(...)
            
            opt.start { response in
                if let err = response.error {
                    completionHandler(response: nil, error: response.error)
                }
                switch(response.statusCode!) {
                case 400:
                    print("Token expired.. getting a new one")
                    self.renewToken(completionHandler: { response in
                        
                    })
                    break
                default:
                        completionHandler(response: response, error: nil)
                    break
                }
            }
        }  catch let error {
            print("\(error)")
        }
    }

But is there a way to redo a specific request again if it fails because I get a statuscode that I did not expect? like for example I get a 400 I want to do another request to get a new token and then redo the request that I was planning to do to get my content from the API.

**Comment by daltoniam** [comment]
No, there currently isn't a way to automatically redo requests by status code. Based on the code above, I would recommend passing the parameters to the requestObj again once the renewToken finishes:
```swift
self.renewToken(completionHandler: { response in
    self.requestObj(ReqMethod, url: url, params: params, completionHandler: completionHandler)
})
```

Should redo the same request as before, but now fall into the case with the renewed token.

**Comment by reshadf** [comment]
Thanks for the reply man appreciate it. But if I do this, I would call it like this, the original method that called requestObj doesn't get the response does it?

**Comment by daltoniam** [comment]
The original method that called with the completionHandler should still get run. Since you are forwarding the completionHandler closure to the next method (same method, recursive call), the original caller should be the one that gets the response, since it is the actual "implementation" of the completionHandler closure. High order functions and recursion and be super handy :smile:.

**Comment by matheuztavarez** [comment]
Worked perfectly! Thanks a lot!!!!! :D
