### ISSUE TITLE
Handling Timeout to Recall the Function

### ISSUE THREAD

**Issue by matheuztavarez** [daltoniam/SwiftHTTP#187]
Hi,

Is there any way that I can handle the time out, like, if it takes more than 2 seconds it cancels the previous request and call it again? I found some code and the timeoutInterval setting but I don't know how to call the function again based on it, and on the code I found it would just work like 
"let opt = HTTP(req)" ( https://github.com/daltoniam/SwiftHTTP/issues/177 ) so I don't know how to change to a GET or POST... 
Would be there any way to do it?

Thanks in advance :)

**Comment by daltoniam** [comment]
I would suggest changing the `timeoutInterval` to 2 seconds. Then in the `onFinish` closure check if the NSError that is returned is a timeout error code. If it is, retry the request. You should be able to call the function again by using recursion as I suggested in #186.

**Comment by matheuztavarez** [comment]
Hey man! Thanks for the answer,
But Im still not able to change the timeout interval! :(

my code is being basically:
```
do{
let opt = try HTTP.PUT( link , parameters:  ["authentication_token": token])
                    opt.start { response in
                        if let obj: AnyObject = response.data {

}
}
} catch error{
print(error)
}
```

Inside I treat the status and do my stuff as normal, but I can't find where I can change the timeout interval..
Am I doing something wrong or should I do something different?

**Comment by daltoniam** [comment]
Two ways you can do it. The easiest way is to use the global handlers to change the timeoutInterval on all HTTP created with the factory methods like so:

https://github.com/daltoniam/SwiftHTTP#global-handlers

**Comment by matheuztavarez** [comment]
Im sorry for the number of questions, but I tried this without success... Where should I put this bunch of code?

```
 HTTP.globalRequest { req in
            req.timeoutInterval = 5
        }
```

I tried before and after the " let opt = try HTTP.PUT .... " with no success..
And it need to call this every time I do a request, or in every view? Or if I call it once it will set the time out for every session already?

**Comment by daltoniam** [comment]
the `globalRequest` only needs to be called once before any of the HTTP factory methods. You can put it in your app delegate or wherever you think is best for initial configuration of your HTTP requests.

**Comment by matheuztavarez** [comment]
Ok, so now I get 

Type HTTP has no member globalRequest

:((

**Comment by daltoniam** [comment]
Well it was a fairly recent add, so you need to make sure you have the latest version `1.0.2`.

https://github.com/daltoniam/SwiftHTTP/blob/master/CHANGELOG.md

**Comment by matheuztavarez** [comment]
Worked perfectly! Thanks a lot man!! :D
