### ISSUE TITLE
Does the start() method run in the background?

### ISSUE THREAD

**Issue by daiKratos** [daltoniam/SwiftHTTP#188]
Do I need to write some code like this? Or the start() method wrap background thread for us? 
Async.background {
do {
                let opt = try HTTP.GET(url)
                opt.start { response in
                    if let err = response.error {
                        print("error: \(err.localizedDescription)")
                        return
                    }
                }
            } catch let error {
                print("got an error creating the request: \(error)")
            }
}

**Comment by reshadf** [comment]
Writing a background thread is not necessary. Its already in background. Although if you need to place/update a view make sure you use GCD to do that on the main thread again.

**Comment by daltoniam** [comment]
thanks @reshadf.

**Comment by daiKratos** [comment]
thanks @reshadf
