### ISSUE TITLE
The platform of the target `sherpawatchapp Extension` (watchOS 2.0) is not compatible with `SwiftHTTP (1.0.2)`, which does not support `watchos`.

### ISSUE THREAD

**Issue by evgeniynet** [daltoniam/SwiftHTTP#195]
Want to use it on watchos 2

pods shows:

The platform of the target `sherpawatchapp Extension` (watchOS 2.0) is not compatible with `SwiftHTTP (1.0.2)`, which does not support `watchos`.

now i got Target 'SwiftHTTP' of project 'Pods' was rejected as an implicit dependency for 'SwiftHTTP.framework' because it doesn't contain platform 'watchsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'

**Comment by daltoniam** [comment]
I haven't tried building SwiftHTTP in a watchOS project yet. I will try to do that soon, pull request welcomed.

**Comment by daltoniam** [comment]
`1.0.3` was released which should resolve this. Any questions let us know.

**Comment by evgeniynet** [comment]
thanks
