### ISSUE TITLE
Problem setting up an PUT-Request

### ISSUE THREAD

**Issue by hengel2810** [daltoniam/SwiftHTTP#196]
Hello,

I have an problem by setting up an put request with SwiftHTTP. I'm trying since hours but it still won't work.

This is the request I need in swift:
<img width="577" alt="bildschirmfoto 2015-11-16 um 21 52 59" src="https://cloud.githubusercontent.com/assets/11571150/11194530/edf8e8ec-8cac-11e5-9535-79d00a5ae9c2.png">

I hope anyone can help me.

**Comment by acmacalister** [comment]
Adapting the README example to your image above.

```swift
let vals = ["id": 97, "value": true]
let params = ["datapoints_values": [vals], "command": 3]
do {
    let opt = try HTTP.PUT("http://192.168.178.62/rest/datapoints/values", parameters: params)
    opt.start { response in
    //do things with response...
    }
} catch let error {
    print("got an error creating the request: \(error)")
}
```

**Comment by hengel2810** [comment]
Thank you for your answer.
I need to set the Cookie-Header for auhentification, how I had to implement the headers?

**Comment by hengel2810** [comment]
It doesn't work. The server answers, that there is a JSON-syntax error.

I think I need the following as a string in the raw bodydata, but how can I implement that with SwiftHTTP?

Raw bodydata:
`{datapoints_values: [{id: 97, value: true}], command: 3}`

**Comment by reshadf** [comment]
Its because you are not sending it as JSON.. 

Change to let opt = try HTTP.New("http://192.168.178.62/rest/datapoints/values", method: .PUT, requestSerializer: JSONParameterSerializer()) instead of the one you have right now

**Comment by hengel2810** [comment]
I've implemented the following code, but now I don't get any answer.


        let url = "\(self.url)/rest/datapoints/values"
        let headers = [
            "Cookie": "user=\(self.userID)"
        ]
        
        let vals = ["id": 97, "value": true]
        let params = ["datapoints_values": [vals], "command": 3]
        do {
            let opt = try HTTP.New(url, method: .PUT, parameters: params, headers: headers, requestSerializer: JSONParameterSerializer())
            opt.onFinish = { response in
                if let err = response.error
                {
                    print("error: \(err.localizedDescription)")
                    return //also notify app of failure as needed
                }
                print("opt finished: \(response.description)")
            }
        } catch let error
        {
            print("got an error creating the request: \(error)")
        }

**Comment by hengel2810** [comment]
Ah, sorry. I found the problem. I didn't implement the serialize protocol-method. Now it works. Thank you both for your help.

**Comment by acmacalister** [comment]
Sounds good. Glad you got it figured out. @reshadf thanks for the help.
