### ISSUE TITLE
Setting Timeout.

### ISSUE THREAD

**Issue by ankit1ank** [daltoniam/SwiftHTTP#197]
How do I set the timeout of the HTTP request?

Thanks is advance.

**Comment by acmacalister** [comment]
See #177.

SwiftHTTP uses protocol extensions now, so you have direct access to the `NSMutableURLRequest` You should set your `timeoutInterval` there.

https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSMutableURLRequest_Class/#//apple_ref/occ/instp/NSMutableURLRequest/timeoutInterval

So here would be an example:

```swift
if let req = NSMutableURLRequest(urlString: "http://domain.com") {
    do {
        try req.appendParameters(["hello": "there"])
        req.addValue("custom", forHTTPHeaderField: "header")
        req.timeoutInterval = 10 // here we set the timeout!
        let opt = HTTP(req)
        opt.start { response in
            //do stuff
        }
    } catch let error {
        print("couldn't serialize the paraemeters: \(error)")
    }
}
```

or use the global handler as specified in the docs

https://github.com/daltoniam/SwiftHTTP#global-handlers

```swift
//modify NSMutableURLRequest for any Factory method call (e.g. HTTP.GET, HTTP.POST, HTTP.New, etc).
HTTP.globalRequest { req in
    req.timeoutInterval = 5
}
```
