### ISSUE TITLE
Some dictionary parameter problem

### ISSUE THREAD

**Issue by yoll522** [daltoniam/SwiftHTTP#199]
hi, may I ask a question

i want a Json like that :
```
{
"selectUser":
   {
      "1":"a",
      "2":"b"
   },
"GroupName":"name"
}
```

So I tried the following code
```
let params: Dictionary<String, AnyObject> =
             ["selectUser": ["1": "a", "2": "b"], "GroupName": "name"]

let opt = try HTTP.POST(urlAddress, parameters: params)
```

but the server always return ```json_decode() expects parameter 1 to be string, array given```

when I use ```NSLog()``` to look```params["selectUser"]```, the value is array, not dictionary 
![Image](http://i.imgur.com/MysDUMF.png)

could you help me what could be the problem?

Thanks for the help
   best regards

**Comment by daltoniam** [comment]
Yeah I am not sure why it would come in as an array, but it might be because you aren't using the JSONParameterSerializer.

https://github.com/daltoniam/SwiftHTTP#json-request-serializer

```swift
let opt = try HTTP.POST(urlAddress, parameters: params, requestSerializer: JSONParameterSerializer())
```

**Comment by yoll522** [comment]
thank you for your help

I ask the web admin, he tell me the parameters must be convert to string on his web

so I try to following code

```
let selectDic = ["1": "a", "2": "b"]
let selectData = try NSJSONSerialization.dataWithJSONObject(selectDic, options: NSJSONWritingOptions(rawValue: 0))
let selectString = NSString(data: selectData, encoding: NSUTF8StringEncoding) as! String
let test = ["select_user": selectString, "group_name": "name"]
```

it can work.

thank you again, and sorry for my poor English
