### ISSUE TITLE
Response Method not working to parse json

### ISSUE THREAD

**Issue by javierC1988** [daltoniam/SwiftHTTP#201]
Hi Dalton sorry again me. I have an issue with Response method. I attach you an image.

Thanks

Thanks a lot

**Comment by daltoniam** [comment]
I think this is a JSONJoy issue and I don't know without seeing the `Response` object, but I am going to guess that the `Response` object hasn't implemented the JSONJoy protocol. See the JSONJoy example here:

https://github.com/daltoniam/JSONJoy-Swift#example

```Swift
struct Response : JSONJoy {
    init() {
    }
    init(_ decoder: JSONDecoder) {
    }
}
```

**Comment by javierC1988** [comment]
yes that was right , completely my mistake. But I create now my own objects and response allways is nil. I got the description of the get call and the object is correct. But in the parser not getting I need. I attach you screens.

<img width="386" alt="error_json4" src="https://cloud.githubusercontent.com/assets/9955461/11660005/051fefd2-9d99-11e5-9fb5-ee2d9e09e870.png">

<img width="813" alt="error_json1" src="https://cloud.githubusercontent.com/assets/9955461/11659969/d329cc64-9d98-11e5-8404-861dafe0b7e4.png">
<img width="495" alt="error_json2" src="https://cloud.githubusercontent.com/assets/9955461/11659968/d328f172-9d98-11e5-850a-d473b769a657.png">
<img width="503" alt="errpr_json3" src="https://cloud.githubusercontent.com/assets/9955461/11659970/d32c09ca-9d98-11e5-8b79-ced61d968ff6.png">

First screen is the object. Second one is how I'm parsing and the others are the reult of the parsed object and the description. Please help me to solve this issue.

Thanks a lot

**Comment by daltoniam** [comment]
I am going to guess that your JSON structure isn't what you are expecting, probably a have a key nested differently then expected. I can't say for certain without knowing what your JSON structure looks like though.
