### ISSUE TITLE
Carthage installation issue

### ISSUE THREAD

**Issue by reshadf** [daltoniam/SwiftHTTP#206]
Hi,

I used to download SwiftHTTP and include it in my project manually since it was my only dependency in the project. Now that I have multiple I started using carthage. Unfortunately when Using Carthage as soon as I build the app to test on my device and when the "SwiftHTTP" job kicks in somewhere I get the following in my console and the app stops. 

SwiftHTTP was compiled with optimization - stepping may behave oddly; variables may not be available.

How can I fix this?

**Comment by acmacalister** [comment]
I'm not sure what you mean. We don't personally use Carthage, so we are not sure. Do you have any more info?

**Comment by reshadf** [comment]
Its because SwiftHTTP compiles for release rather than for debug. I didn't really figure out how to fix that by checking carthage documentation.

**Comment by daltoniam** [comment]
Well release would make sense in most contexts. I would only think you would want debug for debugging :smile:. I would assume Carthage has to work with release built frameworks, but I don't know enough about it to say why it isn't working in your project. The error doesn't look like something that would keep it from building (unless maybe something like treat warnings like errors was on).
