### ISSUE TITLE
This bundle is invalid when submitting the app - The Info.plist file is missing or could not be read.

### ISSUE THREAD

**Issue by Gabsao** [daltoniam/SwiftHTTP#207]
Hello,
I'm facing an issue with the library when i try to submit the app to Apple. I can "Archive" the app with no problem...but when I submit the app I automaticaly receive an Email from Apple with the following Error : 

> This bundle is invalid - The Info.plist file for SwiftHTTP.framework is missing or could not be read.
> Once these issues have been corrected, you can then redeliver the corrected binary.
> Regards,

Wich is really weird beacause the plist file is in the project and the project can be compiled with no problem... After running some tests, I figured that the project is running on the simulator but not on a real device. and I get the following on the Real device ::
> dyld: Library not loaded: @rpath/libswiftSecurity.dylib
> Referenced from: /private/var/mobile/Containers/Bundle/Application/C58E0EBF-6908-40F9-AE41-F71EE1910ACD/XXXXXX.app/Frameworks/SwiftHTTP.framework/SwiftHTTP
> Reason: image not found

I think that I added correctly the library like specified in the readme :: 

![capture d ecran 2016-01-09 a 19 01 29](https://cloud.githubusercontent.com/assets/12788043/12217539/f6b7aae6-b703-11e5-8b7b-16e00781a83c.png)

(Just for info, the project need to embed the Google-Mobile-Ads-SDK and had to turn off the "Enable Bitcode")

I hope someone had the same issue and can give some hints...because I'm running out of ideas....
Thanks in advance for your cooperation.

**Comment by acmacalister** [comment]
I would guess your issue is needing to add the copy framework phase as outlined in the README to run on real devices.

https://github.com/daltoniam/SwiftHTTP#add-copy-frameworks-phase
