### ISSUE TITLE
add body parameters

### ISSUE THREAD

**Issue by reshadf** [daltoniam/SwiftHTTP#209]
Hi is there a method for adding body parameters?

**Comment by daltoniam** [comment]
All parameters are added to the body by default, unless required to be in the URL as the HTTP spec defines (GET, DELETE, HEAD, etc). If you want JSON in the body you can use the JSONRequestSerializer.

**Comment by reshadf** [comment]
Oh sweet, do you have an example of that?

**Comment by reshadf** [comment]
Ok got it thanks!
