### ISSUE TITLE
DELETE method with body

### ISSUE THREAD

**Issue by davidalonso** [daltoniam/SwiftHTTP#211]
HTTP specification does not indicate that DELETE requests cannot have body.

DELETE HTTPVerb should be removed from isURIParam() method and let that decision to the developer.

**Comment by daltoniam** [comment]
That is true, and the developer can still build a request as they need with `NSMutableRequest` methods provided in SwiftHTTP. The factory method of DELETE however is built to do the most common case of DELETE having the parameters in the URL (as many other networking libraries do). Many web servers ignore the body of a DELETE request so it makes sense in the general case to put them in the URL.
