### ISSUE TITLE
Sending a string as parameters in post request

### ISSUE THREAD

**Issue by ankit1ank** [daltoniam/SwiftHTTP#213]
The library allows to send an array or a dictionary as parameters, but how do I send a string as parameters in a POST request?

**Comment by acmacalister** [comment]
The README has an example of sending a string as a parameter in a POST request. Parameters generally can't just be strings and have to be encoded in some format such an HTTP form encoding, JSON, etc. If your web service is actually expecting just a raw string in your POST body you can create a custom serializer to do this by implementing the `HTTPSerializeProtocol` like so:

https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Operation.swift#L18

```swift
let params = ["param": "param1"] // a string as an HTTP parameter
do {
    let opt = try HTTP.POST("https://domain.com/new", parameters: params, requestSerializer: requestSerializer: CustomParameterSerializer())
    opt.start { response in
    //do things...
    }
} catch let error {
    print("got an error creating the request: \(error)")
}
```
