### ISSUE TITLE
Connect with cert.pem key.pem ca.pem 

### ISSUE THREAD

**Issue by alessiofx** [daltoniam/SwiftHTTP#217]
With your library if possible connect server with SSL client Auth?
I send 3 file for authentication:
ca.pem, cert.pem, key.pm

thanks

**Comment by alessiofx** [comment]
ok, but how to insert the other 2 files
thanks

**Comment by daltoniam** [comment]
At this point I'm not exactly sure what you are trying to accomplish. SSL pinning should only use one certificate or public key. You can generally add the certificate or public key to your app bundle as the docs show.

**Comment by alessiofx** [comment]
I use this:
curl https://$HOST:3333/photo/json \
  --cert ~/user/cert.pem \
  --key ~/user/key.pem \
  --cacert ~/user/ca.pem

how to with Swift and your library?

thanks

**Comment by acmacalister** [comment]
I looked into the SSL Pinning some more. You need to use a DER encoded cert, that you can generally pull from your server with this command:

```
openssl s_client -connect myserver:443 </dev/null 2>/dev/null | openssl x509 -outform DER > myserver.cer
```

You can then use put the `myserver.cer` into your app bundle, follow the docs to enable the SSL Pinning and that is usually all that is required. I'm not sure why the client would need the cert, key and cacert to do SSL Pinning and not sure I can offer any guidance there.
