### ISSUE TITLE
EXC_BAD_ACCESS in Requests.swift (collect.appendContentsOf...)

### ISSUE THREAD

**Issue by floscom** [daltoniam/SwiftHTTP#223]
Line **122** and **151** - collect.appendContentsOf(subParam.createPairs(useKey))

This problem only happens when i use my release schema. (no zombie objects etc.). @pappzsolt100 had already posted an issue, but this workaround didn't work for me - issue: #155 

I've replaced the **collect.appendContentsOf** with an iteration through the array:

```swift
...
for s in subParam.createPairs(useKey) {
 collect.append(s)
}
...
```

**Comment by acmacalister** [comment]
@floscom interesting. Can you provide the params you were using?

**Comment by floscom** [comment]
@acmacalister here are two examples of arrays I use.

**Example 1:**
```swift
var params = Dictionary<String,AnyObject>()
params["last_updated"] = 1234567890
params["ids"] = [1,2,3,4,5,6,7]
```

**Example 2:**
```swift
var params = Dictionary<String,AnyObject>()
params["last_updated"] = 1234567890
params["new_1"] = ["title": "Name of the new entry", "some": "other"]
```

The error only occurs when I run my app in realease mode. Therefore I think, that something goes wrong with the compiler.

**Comment by floscom** [comment]
this is the whole rewrited extension:

```swift
extension Dictionary: HTTPParameterProtocol {
    public func paramType() -> HTTPParamType {
        return .Dictionary
    }
    public func createPairs(key: String?) -> Array<HTTPPair> {
        var collect = Array<HTTPPair>()
        for (k, v) in self {
            if let nestedKey = k as? String, let nestedVal = v as? AnyObject {
                let useKey = key != nil ? "\(key!)[\(nestedKey)]" : nestedKey
                if let subParam = nestedVal as? Dictionary { //as? HTTPParameterProtocol <- bug? should work.
                    collect.appendContentsOf(subParam.createPairs(useKey))
                } else if let subParam = nestedVal as? Array<AnyObject> {
                    for s in subParam.createPairs(useKey) {
                        collect.append(s)
                    }
                } else {
                    collect.append(HTTPPair(key: useKey, value: nestedVal))
                }
            }
        }
        return collect
    }
}

**Comment by AdrienGiboire** [comment]
I have the same issue. When changing the optimization level of the pod compilation to none, I can not reproduce the bug.

**Comment by AdrienGiboire** [comment]
The issue is due to SwiftHTTP defaulting to `HTTPSerialization`. I've set the serializer to `JSONParameterSerializer`.

```
let request = try HTTP.PUT(self.urlFor(path), parameters: requestOptions, headers: headers, requestSerializer: JSONParameterSerializer())
```

**Comment by daltoniam** [comment]
Thanks all for the feedback. I think this might be a bug in the compiler in the way protocols are being used. I plan to address this in the Swift 3 release, but PRs are welcomed as I haven't had time much time to investigate this.

**Comment by daltoniam** [comment]
The Swift 3 branch has been released. My hope is that should resolve the issue we where seeing with the optimization level and the crashing. Let me know if this is still an issue with the Swift 3 release (2.0.0) and I will investigate further. Thanks!

**Comment by daltoniam** [comment]
Haven't heard anything so I'm gonna assume all is good 😄. If anyone is having issue with Swift 3 please let us know.
