### ISSUE TITLE
multiFormHeader key can't escaped when use "multipart/form-data"

### ISSUE THREAD

**Issue by singi521** [daltoniam/SwiftHTTP#224]
if key escape , then server side can't parse array key!

i find answer, is right?

A value of "application/x-www-form-urlencoded" means that your POST body will need to be URL encoded just like a GET parameter string. A value of "multipart/form-data" means that you'll be using content delimiters and NOT url encoding the content.

http://stackoverflow.com/questions/6603928/should-i-url-encode-post-data

**Comment by daltoniam** [comment]
The latest checkin on master should resolve this.
