### ISSUE TITLE
HTTP.POST method is sending GET requests instead of POSTs

### ISSUE THREAD

**Issue by DominikPalo** [daltoniam/SwiftHTTP#225]
When I'm calling `HTTP.POST()` method to send a POST requests to the server, HTTP request with method GET is delivered to the server. HTTP.PUT works fine. I'm using latest version of library - 1.0.5.

**Comment by DominikPalo** [comment]
After I changed the URL to use https instead of http, POST works fine... but when I have http in my url, HTTP.POST generates GET requests (and it seems that it is not a server problem - using POSTMAN tool POSTs to http and https works as expected)

**Comment by acmacalister** [comment]
I just the latest version of SwiftHTTP yesterday and could not reproduce this behavior. Since it uses `NSURLSession` I'm not sure how HTTP or HTTPS would make a difference. Do you have any sample code to demo this issue?
