### ISSUE TITLE
caching / clacks-protocol issue?

### ISSUE THREAD

**Issue by schnoddelbotz** [daltoniam/SwiftHTTP#226]
Hi,

while implementing my toy project, I stumbled upon the fact that my OS X app caches HTTP requests (stored in a SQLite DB, namely `~/Library/Caches/<BundleID>/Cache.db`).
My app runs in different user contexts - this produced different results when executing identical GET requests using SwiftHTTP, which made me aware of the user-based disk caching taking place at all.

I skimmed through [Apple's CachePolicies documentation](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/URLLoadingSystem/Concepts/CachePolicies.html) and read:

> By default, the data for a request is cached based on the request’s cache policy, as interpreted by the NSURLProtocol subclass that handles the request.

Before diving deeper into CachePolicies docs, I searched for "cache" in SwiftHTTP sources, found nothing and decided to create this issue here first... to ask for help: Do you have any plans on also "simplifying" CachePolicies? :-) -- Or... did I just miss something? Is there possibly a Info.plist setting to keep NSURL from caching?

I admit I still have to look into this myself some more: Up to now, I don't understand why underlying NSURL caches at all, given this particular response header for a GET request ([VLC's sparkle feed](http://update.videolan.org/vlc/sparkle/vlc-intel64.xml)):

< HTTP/1.1 200 OK
< Server: nginx/1.9.15
< Date: Wed, 11 May 2016 20:08:35 GMT
< Content-Type: text/xml
< Content-Length: 16456
< Connection: keep-alive
< Last-Modified: Wed, 11 May 2016 15:56:48 GMT
< ETag: "57335640-4048"
< Accept-Ranges: bytes
< X-Clacks-Overhead: GNU Terry Pratchett

The [clacks-protocol RFC draft](https://github.com/clacks-overhead/clacks-protocol/blob/master/middle.mkd) clearly states:

> Due to this any message with the Clacks header MUST be considered equivalent to the no-cache header defined in Section 5.2.1.4 (of RFC 7234)

Whether anybody already filed a bug with apple about missing clacks-support in NSURL? ;)
For me, it didn't even revalidate the ETag; the request was always served directly off the disk cache, regardless of app restarts.

Thanks a ton for SwiftHTTP!

**Comment by acmacalister** [comment]
Interesting. We hadn't planned on doing on anything with cache policies, but definitely wouldn't be against looking into, especially if the defaults behave strangely. I will have to look into this. In the meantime, does configuring the `requestCachePolicy` to  `.ReloadIgnoringLocalCacheData` ignore the local cache?

https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLSessionConfiguration_class/#//apple_ref/occ/instp/NSURLSessionConfiguration/requestCachePolicy

**Comment by shev-vadim-net** [comment]
Hi, I also faced that cache issue, but couldn't find how can I configure CachePolicy in SwiftHTTP. I think it would be a good idea to make it configurable via globals like auth, security.

I've implemented the feature for my needs ([commit](https://github.com/shev-vadim-net/SwiftHTTP/commit/1fae7951e17a8c2bcc08dec69bf5f0ee6869e4c8)) but will be glad if you can do something similar.

Thanks for the nice library!

**Comment by daltoniam** [comment]
You can configure the cache policy through the standard `URLRequest` object in version 3.0.0. Global configuration can also be done via the globalRequest closure.

https://github.com/daltoniam/SwiftHTTP#global-handlers
