### ISSUE TITLE
multiple request

### ISSUE THREAD

**Issue by OskrNav** [daltoniam/SwiftHTTP#228]
hi 

there is a method for I can request multiple url and  get it  when all urls are finished  

thanks in advance

**Comment by daltoniam** [comment]
I would use an NSOperationQueue as SwiftHTTP supports it:
https://github.com/daltoniam/SwiftHTTP#operation-queue

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSOperationQueue_class/

It should be as simple as adding all your request to the operation queue then checking waiting for `waitUntilAllOperationsAreFinished` on the operation queue.

**Comment by OskrNav** [comment]
thanks a lot
