### ISSUE TITLE
Use of unresolved identifier 'HTTPTask'

### ISSUE THREAD

**Issue by dzielski** [daltoniam/SwiftHTTP#229]
Hi, Did the pod init and pod install, and then did import SwiftHTTP and now getting unresolved identifier on the HTTPTask() command. Xcode 7.3.1 and building for 9.0

import UIKit
import SwiftHTTP

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        var request = HTTPTask()   <- Use of unresolved identifier 'HTTPTask'
        
        
        // Do any additional setup after loading the view, typically from a nib.
    }

Thanks.

**Comment by acmacalister** [comment]
The `HTTPTask` class hasn't been in SwiftHTTP for quite a while. Are you trying to use a swift-2-bc branch? As that code no longer exist in new versions of SwiftHTTP.

**Comment by dzielski** [comment]
Thanks for the answer @acmacalister - I saw a solution online using HTTPTask to convert some Objective-C code to Swift and it was using HTTPTask. Your information is most helpful. I will look to do it another way.
