### ISSUE TITLE
Multiple upload file as array

### ISSUE THREAD

**Issue by zenvarlab** [daltoniam/SwiftHTTP#230]
Hello how to pass multiple images as array ?

I try using ["images":[Upload(fileUrl:url1), Upload(fileUrl:url2), Upload(fileUrl:url3)]] as parameters when request POST

still no luck, is't possible to send image as array object?

**Comment by daltoniam** [comment]
I don't see why this won't work. It should come across to your server as an array of images (images[]). Can you provide any more details? The data the server is receiving?
