### ISSUE TITLE
Upload file from photo library

### ISSUE THREAD

**Issue by kshysius** [daltoniam/SwiftHTTP#231]
How to upload image / video from image gallery? 

image URL:
assets-library://asset/asset.JPG?id=94B1F02C-D39A-4E4E-8DAF-001644D9C0A6&ext=JPG

**Comment by daltoniam** [comment]
You need to either read the asset off disk and use the data to create an `Upload` object, or pass that URL in an `Upload` object. See https://github.com/daltoniam/SwiftHTTP#upload for more details.

https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Upload.swift#L95

https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Upload.swift#L108

**Comment by amitg02** [comment]
Domain=NSCocoaErrorDomain Code=256 "The file “asset.JPG” couldn’t be opened." UserInfo={NSURL=assets-library://asset/asset.JPG?id=106E99A1-4F6A-45A2-B320-B0AD4A8E8473&ext=JPG}
got above error while uploading from assets
