### ISSUE TITLE
Not able to post data(NSData) in body 

### ISSUE THREAD

**Issue by vishundayal** [daltoniam/SwiftHTTP#234]
Hi ,
Could anybody please tell me, using this library how can I send a custom data (NSData) through post request? 

Thanks
Vishun

**Comment by daltoniam** [comment]
By NSData, I assume you mean uploading a file. See this:

https://github.com/daltoniam/SwiftHTTP#upload

https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Upload.swift#L109

Simply follow the same upload example from the README and just change the Upload object to use the NSData file upload version instead of the fileURL one.

```swift
let yourData = //... your NSData object
do {
    let opt = try HTTP.POST("https://domain.com/new", parameters: ["aParam": "aValue", "file": Upload(data: yourData, fileName: "myFile", mimeType: "image/png")]) //your whatever your mime type is
    opt.start { response in
    //do things...
    }
} catch let error {
    print("got an error creating the request: \(error)")
}
```

mimeType list:
https://www.sitepoint.com/web-foundations/mime-types-complete-list/

**Comment by vishundayal** [comment]
I want to set a json string as nsdata into body. I did not find a way to set body like we do in case of NSMutableRequest httpBody

**Comment by daltoniam** [comment]
Ah, that adds context, thank you 😄. SwiftHTTP is built to serialize the parameters for you, so if you want to send the HTTP body as data yourself, you can do that with a bit more code:

https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Operation.swift#L385
https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Operation.swift#L243

```swift
do {
    guard let req = NSMutableURLRequest(urlString: yourURL) else { return }
    req.verb = .POST
    req.HTTPBody = //your data
    let opt = HTTP(req)
    opt.start { response in
        if let err = response.error {
            print("error: \(err.localizedDescription)")
            return //also notify app of failure as needed
        }
        print("opt finished: \(response.description)")
        //print("data is: \(response.data)") access the response of the data with response.data
    }
} catch let error {
    print("got an error creating the request: \(error)")
}
```
