### ISSUE TITLE
  Excuse me, do you support IPv6?

### ISSUE THREAD

**Issue by 285298984** [daltoniam/SwiftHTTP#237]
The audit was rejected because it was not compatible with IPv6

**Comment by daltoniam** [comment]
SwiftHTTP doesn't do any specific with IPv6. This is all handled by the underlining NSURLSession APIs, thus should be supported in proper IPv6 setup of NSURLSession. I'm not sure what audit you are referring to, but there shouldn't be anything specific in SwiftHTTP to cause an issue. 

https://developer.apple.com/videos/play/wwdc2015/719/
