### ISSUE TITLE
GET request with array params crash after code optimalization

### ISSUE THREAD

**Issue by kkunowski** [daltoniam/SwiftHTTP#238]
Crash happens only for Swift Optimalization Level "Fast" that is a default for "Release' configuration. For "None" level used by default in debug it does not happens.

**Comment by acmacalister** [comment]
What version of SwiftHTTP are you using? Are you using mixed params type? Sounds like this might be related to #223, which the fixes in master might address. Can you try out that and see if that fixes the issue? Otherwise sample code or app would be great to reproduce the issue.
