### ISSUE TITLE
How to get the downloaded file url in the latest version?

### ISSUE THREAD

**Issue by iori57** [daltoniam/SwiftHTTP#240]
Before Swift 2.0 I was using the library to download file and I was able to get the file location using
if let url = response.responseObject as? NSURL

Just updated my code to Swift 2.0 and noticed a bunch of stuff has been broken, so I downloaded the latest version and notice a lot of syntax has changed :)

Seems that responseObject is no longer available, how can I get the file URL?

Thanks for the awesome plugin by the way!

**Comment by daltoniam** [comment]
I haven't had the time to implement the download method APIs yet. Issue #192 shows how to download until that is complete.

P.S. I plan to do some work on my open source stuff over the weekend for Swift 2.3 and Swift 3. I think I will be able to squeeze in some download API support!

**Comment by daltoniam** [comment]
The Swift 3 version (2.0.0) has been released with a new download method. See here:

https://github.com/daltoniam/SwiftHTTP#download
