### ISSUE TITLE
Swift 3 ?

### ISSUE THREAD

**Issue by matheusfrozzi** [daltoniam/SwiftHTTP#241]

**Comment by daltoniam** [comment]
Hopefully coming this weekend.

**Comment by Elshad** [comment]
@matheusfrozzi thanks for swift 3 migration 👍 

https://github.com/matheusfrozzi/SwiftHTTP

**Comment by Elshad** [comment]
@daltoniam thanks for this library 👍

**Comment by RichardBoyder** [comment]
Is cocoa pods updated to swift 3 ?

**Comment by MauriceCheung-GreyboxSolutionsInc** [comment]
I am also waiting for Cocoapods update

**Comment by gweiss27** [comment]
Would love the cocoa pods update! Thanks in advance! :)

**Comment by daltoniam** [comment]
The Swift 3 version has been pushed to CocoaPods! Version 2.0.0.
