### ISSUE TITLE
ERROR keep return unsupported URL

### ISSUE THREAD

**Issue by dayvon** [daltoniam/SwiftHTTP#243]
urgent Please Help

before i update my xcode it working fine, after update and i convert all my source to Swift 2.3
the respond keep return  unsupported URL

i had try many method it still not working

**Comment by durd07** [comment]
The solution is change code at Request.swift 237 
from self.URL = NSURL(string: "\(u.absoluteString)\(para)\(queryString)") 
to self.URL = NSURL(string: "\(u)\(para)\(queryString)")

**Comment by dayvon** [comment]
Thankyou very much it work
