### ISSUE TITLE
Can't upload image converted to NSData to server

### ISSUE THREAD

**Issue by eciftcioglu** [daltoniam/SwiftHTTP#244]
//This is how I update my parameter before posting it. Filearray is a Foundation.Data type array(New NSData format).The rest of the parameters I send are received by the server except the images array. I want to know if there is any problem with my code. I know the server side is fine because I tested it by sending an image using  postman and it seems to work fine. I can post more of the code if needed.Thanks for the help.

for index in 0..<filearray!.count {
            
            params.updateValue(Upload(data: filearray![index], fileName: "resim_"+String(index)+".jpg", mimeType: "image/jpeg"), forKey: "files[" + String(index) + "]")
            
        }

**Comment by daltoniam** [comment]
I don't see anything wrong with the Upload object off hand. It might be that it is being serialized differently than expected though (depending on how many files you are uploading). Check out #232 for more info on multiple file uploads.
