### ISSUE TITLE
Error 415

### ISSUE THREAD

**Issue by ivangarcialopez** [daltoniam/SwiftHTTP#245]
Hello,

First of all thanks for the library, I really appreciate your work.

After migrating my project to Swift 3 I receive a 415 error from a Web Service which worked in Swift 2. Is is something related to the operation class?

This is my code
        var errores:String = ""
        let Url = "\(GlobalConstants.URLBaykus)/api/login"
        _ = URLSession.shared
        
        let params = ["email":""+ETUser.text!, "password":""+ETPassword.text!]
        
        do {
            let opt = try HTTP.POST(Url, parameters: params)
            opt.start { response in
                if let err = response.error {
                    
                    let data = response.collectData as! Data
                    let str = NSString(data: data, encoding: String.Encoding.utf8.rawValue)
                    if str != nil && str != ""
                    {
                        var errr: NSError?
                        var json:NSDictionary?
						
                        do {
                            json = try JSONSerialization.jsonObject(with: data, options: []) as! NSDictionary
                            // use anyObj here
                        } catch {
                            print("json error: \(error)")
                        }
                        print("Error: \(json)")
                        errores = json?.value(forKey: "Message") as! String
                    }
                    else
                    {
                        errores = err.localizedDescription;
                    }
                    
                    print("error: \(err.localizedDescription)")
                    DispatchQueue.main.async {
                        let alertController = UIAlertController(title: "Warning", message:errores, preferredStyle: UIAlertControllerStyle.alert)
                        alertController.addAction(UIAlertAction(title: "Dismiss", style: UIAlertActionStyle.default,handler: nil))
                        
                        self.present(alertController, animated: true, completion: nil)
                    }
                    return //also notify app of failure as needed

Kind regards,

Ivan

**Comment by daltoniam** [comment]
The Swift 3 version has been released (version 2.0.0)! Upgrading to to the version 2.0.0 should fix the issue now that SwiftHTTP has swift 3 support.

**Comment by cleveralmeida** [comment]
Hi Dailtoniam !

Thank you for the library too !

I was using your library in Swift 2.3 and I've upgraded to Swift 3.0 and the response is getting 415 error yet.
