### ISSUE TITLE
Server get empty body because of unwrapped optional value of charset

### ISSUE THREAD

**Issue by Riaxter** [daltoniam/SwiftHTTP#248]
Hi, I'm making an IPhone app with your library.
It was easy to make connection between my IPhone Client with swift 2 and my server with NodeJS, using SwiftHTTP.
But after I upgraded to Swift 3, server get empty body.
When I send same data in DHC which is HTTP Client in Chrome, it works fine
I sniff my HTTP Request and I found "Content-Type" is different between Normal Request and Bad Request.
Normal Request has "Content-Type : application/json" and Wrong Request which is sent from SwiftHTTP has "Content-Type : application/json;charset = Optional(utf-8)"
I think "Optional" is a bug from your update, you didn't unwrap "Optional" value
So I add "!" in : 
let charset = CFStringConvertEncodingToIANACharSetName(CFStringConvertNSStringEncodingToEncoding(String.Encoding.utf8.rawValue))!
in Request.Swift in your Library
And It works!
Please fix and update this.

**Comment by daltoniam** [comment]
Thanks. Version `2.0.1` has been released.

**Comment by giluna** [comment]
@daltoniam FYI  issue is still not fixed in Version 2.0.1
@Riaxter thank you for the temporary solution!

**Comment by SamDecrock** [comment]
Man, this has been bugging me for hours.

I was debugging it using Postman, using the exact same content-type:

```
application/json; charset=Optional(utf-8)
```

But whatever you set after `charset`, Postman just ignores it and uses the right charset...
