### ISSUE TITLE
Swift3: HTTP.POST() fails to detect and upload files included in parameters (BUGFIX INCLUDED)

### ISSUE THREAD

**Issue by bpollman** [daltoniam/SwiftHTTP#249]
After switching to swift3 in my project and in SwiftHTTP my file uploads have been failing. I've traced it to the containsFile() call in Request.swift at line 351
 
  `   guard let params = parameters as? HTTPParameterProtocol else { return false }`

Not certain why the call is failing, but I fixed it by changing the parameter from 

`public func containsFile(_ parameters: Any) -> Bool `
to 
`public func containsFile(_ parameters: HTTPParameterProtocol) -> Bool `

and removing the need to cast the object at all. 

I'll do a commit and pull request, in the mean time for anyone else

Copy and paste solution: just replace containsFile() function with this: 
```
public func containsFile(_ parameters: HTTPParameterProtocol) -> Bool {
        for pair in parameters.createPairs(nil) {
            if let _ = pair.upload {
                return true
            }
        }
        return false
    }
```

**Comment by Elshad** [comment]
Well done

**Comment by daltoniam** [comment]
Thanks. Version `2.0.1` has been released.
