### ISSUE TITLE
HTTP.Download wrong progress

### ISSUE THREAD

**Issue by pascalbros** [daltoniam/SwiftHTTP#259]
### Issue

Using HTTP.Download, the progress is not correct, it says something like:
0.00123
0.00167
0.00111
0.00353
0.0021
0.00154

## Solution

Line 608 `Operation.swift` Instead of

    func urlSession(_ session: Foundation.URLSession, downloadTask: URLSessionDownloadTask, didWriteData bytesWritten: Int64, totalBytesWritten: Int64, totalBytesExpectedToWrite: Int64) {
            guard let resp = responseForTask(downloadTask) else { return }
            progressHandler(resp, expectedLength: totalBytesExpectedToWrite, currentLength: bytesWritten)
    }

Change `bytesWritten` to `totalBytesWritten`

Cheers, Pascal

**Comment by acmacalister** [comment]
good catch. Thanks!
