### ISSUE TITLE
How can I insert body in PUT and POST request?

### ISSUE THREAD

**Issue by redwolfgang20** [daltoniam/SwiftHTTP#260]
How can I insert body int the request under POST and PUT? so far as what I see based on the documentations I haven't see the body in the request included? thanks 😄

**Comment by daltoniam** [comment]
The body is inserted for you based on the parameters you send and the serializer you use. 

https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Request.swift#L269

https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Request.swift#L300

https://github.com/daltoniam/SwiftHTTP/blob/master/Source/Request.swift#L329

If you want to put in a custom body, you would need to create your own serializer or create your own URLRequest.
