### ISSUE TITLE
How can i change the request cache policy ?

### ISSUE THREAD

**Issue by oziade** [daltoniam/SwiftHTTP#261]
Hello all !

Is there a way to custom the request cache policy with last version  (to set it to `reloadIgnoringLocalCacheData`) ?  
In previous versions, I could implement my own request serializer where the field cachePolicy was available.
But I can't find where to do it in last version. For now, I've put it in the HTTP.New method as a new parameter (I can do a PR if you're interested).

Thanks !

**Comment by acmacalister** [comment]
@oziade sorry for the delay. We actually changed that behavior to use global request handler. It is was pain having to forward the properties every time the class was updated. You can see it in the README here: https://github.com/daltoniam/SwiftHTTP#global-handlers
