### ISSUE TITLE
Problem with Uploading Image

### ISSUE THREAD

**Issue by rhsu0268** [daltoniam/SwiftHTTP#263]
Hi, 

I want to upload an image to a web application that I have running in the backend. But this code snippet is not working. Please advise. 

 let fileUrl = url
        print("--- imageURL ---")
        print(fileUrl)
        print("--- ---")
       
        do {
            //let opt = try HTTP.POST("http://localhost:3000/uploadTest", parameters: ["aParam": "rhsu0268", "file": Upload(fileUrl: fileUrl as URL)])
            let opt = try HTTP.POST("http://localhost:3000/uploadTest", parameters: ["aParam": "rhsu0268", "file": Upload(fileUrl: fileUrl as URL)])
            opt.start { response in
                //do things...
                print("---")
                print(response.description)
                print("---")
            }
        } catch let error {
            print("got an error creating the request: \(error)")
        }

**Comment by gxnews8** [comment]
let opt = try HTTP.POST("http://localhost:3000/uploadTest", parameters: ["aParam": "rhsu0268", "file": Upload(fileUrl: fileUrl)])
Try it

**Comment by acmacalister** [comment]
That upload code looks correct. Where you able to get this working?
