### ISSUE TITLE
"Ambiguous use of 'createPairs'"

### ISSUE THREAD

**Issue by LinusGeffarth** [daltoniam/SwiftHTTP#267]
In `Requests.swift`, I am getting this error: "Ambiguous use of 'createPairs'"
It seems to be confused about the public functions `createPairs(_ key: String) -> Array<HTTPPair>` inside the dictionary and array extensions.

Any ideas what could fix this? Thanks!

**Comment by gxnews8** [comment]
Check your Array<HTTPPair>

**Comment by LinusGeffarth** [comment]
Which array? This error occurs inside the requests file that I pulled from github. I didn't do anything with it yet

**Comment by acmacalister** [comment]
We need some more information here. Maybe the code that you are having a problem with. Are you implementing the `HTTPParameterProtocol` to doing custom?
