### ISSUE TITLE
How to handle timeouts

### ISSUE THREAD

**Issue by jl2378** [daltoniam/SwiftHTTP#270]
Hi, I'm trying to send an http get or post request and then execute some code if the request timed out.

I'm not sure if I can define a timeout handler with this library. Anyone have any ideas?

**Comment by acmacalister** [comment]
Docs have an example on adding timeout handler.

https://github.com/daltoniam/SwiftHTTP#global-handlers

**Comment by optionals** [comment]
version 3.0.0
`HTTP.globalRequest { req in
    req.timeoutInterval = 5.0
    return
}`
Get error: Cannot assign to property: 'req' is a 'let' constant
@daltoniam
