### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by itchingpixels** [daltoniam/SwiftHTTP#274]
Hi,

I'm enjoying using SwiftHTTP, but the latest release was in Oct, and there are quite a few fixes that were merged since then, so currently I'm pointing cocoapods to master/HEAD, which I also feel slightly uncomfortable with.

It'd be great to do another minor release!

Thanks!

**Comment by acmacalister** [comment]
Can do. I will do it tomorrow.

**Comment by anushkmittal** [comment]
bump

**Comment by acmacalister** [comment]
2.1.0 with Swift 4 support is out!
