### ISSUE TITLE
Converting Response in JSON Object 

### ISSUE THREAD

**Issue by hvp1621991** [daltoniam/SwiftHTTP#275]
I am new for Swift Coding Language using this library I got my response correctly, in addition to I need to convert that response to Json Object 

http://192.168.1.118/first_try/get_all_users.php

Status Code:
200

Headers:
Content-Type: text/html; charset=UTF-8
Content-Length: 350
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
X-Powered-By: PHP/5.6.30
Server: Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/5.6.30 mod_perl/2.0.8-dev Perl/v5.16.3
Date: Fri, 26 May 2017 14:36:16 GMT

Payload:
{"products":[{"user_id":"1","user_full_name":"Harshal Pathak"},{"user_id":"2","user_full_name":"Chaitali Parab"},{"user_id":"3","user_full_name":"Aadesh Jadhav"},{"user_id":"4","user_full_name":"Jigar Kothari"},{"user_id":"5","user_full_name":"Vikrant Gunjal"},{"user_id":"6","user_full_name":"a"},{"user_id":"7","user_full_name":"Csc"}],"success":1}

this complete print of response.description
I need to convert last Payload Part into Json Object,
Please help me out
Thanks in advance

**Comment by acmacalister** [comment]
There are several tutorials and libraries for parsing JSON responses. I would suggest you search Github and take a look at a couple of them. Apple also has introduction on how parse JSON using just Apple provided frameworks. You can see that [here](https://developer.apple.com/swift/blog/?id=37).
