### ISSUE TITLE
swift4  memory  issues

### ISSUE THREAD

**Issue by cadaverousblue** [daltoniam/SwiftHTTP#278]
warning this when i run my app in operation.swift:
 
implicit Objective-C entrypoint +[owner.HTTP keyPathsForValuesAffectingIsReady] is deprecated and will be removed in Swift 4
implicit Objective-C entrypoint +[owner.HTTP keyPathsForValuesAffectingIsFinished] is deprecated and will be removed in Swift 4
implicit Objective-C entrypoint +[owner.HTTP keyPathsForValuesAffectingIsExecuting] is deprecated and will be removed in Swift 4

**Comment by daltoniam** [comment]
Resolved in version 3.0.0 (just released).
