### ISSUE TITLE
Carthage fails building SwiftHTTPOSX

### ISSUE THREAD

**Issue by ch4vi** [daltoniam/SwiftHTTP#279]
I tried to update carthage with the latest version and it fails when it tries to build SwiftHTTP

`A shell task (/usr/bin/xcrun xcodebuild -project /Carthage/Checkouts/SwiftHTTP/SwiftHTTP.xcodeproj -scheme SwiftHTTPOSX -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme SwiftHTTPOSX is not currently configured for the clean action.`

If I force to use the previous version v2.1.0 it works.

**Comment by daltoniam** [comment]
SwiftHTTP uses a unified framework as of version 3.0.0. The SwiftHTTPOSX scheme should not exist anymore. Are you using version 3.0.0?

**Comment by ch4vi** [comment]
Currently I'm using v2.1.0 because Carthage fails when I try to update to v3.0.0 with the error that I've put before. I deleted Carthage folders with the previous builds and checkouts and the error still there.

**Comment by acmacalister** [comment]
@ch4vi we understand you are using the older version and have an issue on the new 3.0.0 version. To @daltoniam point, the `SwiftHTTPOSX` scheme no longer exist in 3.0.0, which is being referenced in the build error you posted above. Can you verify that you are using the new scheme for v3.0.0 when building with Carthage?
