### ISSUE TITLE
swift 4.0.x and version 3.0.0, can not set globalRequest timeoutInterval

### ISSUE THREAD

**Issue by optionals** [daltoniam/SwiftHTTP#280]
version 3.0.0
HTTP.globalRequest { req in req.timeoutInterval = 5.0 return }
Get error: Cannot assign to property: 'req' is a 'let' constant

**Comment by mohsenShakiba** [comment]
same here

**Comment by sdduursma** [comment]
I'm also running into this issue.

**Comment by daltoniam** [comment]
3.0.1 has been released with this fix!
