### ISSUE TITLE
API response changes are not reflecting

### ISSUE THREAD

**Issue by nandkishormewara** [daltoniam/SwiftHTTP#283]
Hello, 
I am using SwiftHTTP in my ios app. it's working but whenever changes are made on database the updated values are not reflecting in app 
for exp. if a node value changed from "test" to "test1" then the value still showing in app. even same changes are working on other api test platform
i think it's URLCaching problem

and how to use it "NSURLRequest.CachePolicy" as i searched please provide solution

**Comment by daltoniam** [comment]
I'm not totally certain what you are setting, but if you want to modify your cache settings that can be done through the standard NSURLRequest property. You can either modify the request globally:

https://github.com/daltoniam/SwiftHTTP#global-handlers

or you can create a normal NSURLRequest as modeled in the SSL pinning example:

https://github.com/daltoniam/SwiftHTTP#ssl-pinning
