### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by dennyferra** [daltoniam/SwiftHTTP#3]
Any plans for adding headers to the request and also reading headers from the response?

**Comment by adbeelitamar** [comment]
Sorry to comment on a  closed issue, but response.headers doesn't work for me

(lldb) frame variable -L response.headers
0x7aee0ccc: ([String : String]?) response.headers = Some
(lldb) frame variable -L response.headers["Content-Type"]
error: unable to find any variable expression path that matches 'response.headers[Content-Type]'

**Comment by daltoniam** [comment]
hmmm, not sure why, is the request completing successfully? This example prints out the whole request, including the headers.

```swift
let task = HTTPTask()
task.GET("http://vluxe.io", parameters: nil, completionHandler: { (response: HTTPResponse) in
    println("response is \(response.description)")
})
```
The debugger in Swift isn't always great at inspecting variable so you might want to try this as well:

```swift
if let heads = self.headers {
    for (key, value) in heads {
        println("\(key): \(value)\n")
    }
} else {
	println("no headers found")
}
```

**Comment by cwoloszynski** [comment]
This seems to have been lost when you refactored the API.  I don't see this in HTTPSerializeProtocol or JSONParameterSerializer. 

I did a quick review of the code and I did not see any way with the new API to set the Authorization header.  I am also looking to use AWT for my app that is using SwiftHTTP.
