### ISSUE TITLE
Having difficulties to deploy to real machine

### ISSUE THREAD

**Issue by ldong** [daltoniam/SwiftHTTP#37]
It works great on the simulator, but it crashes once I deployed to the real machine.

Environment: Maverick 10.9.5, Xcode 6.1, iOS 8.1

`dyld: Library not loaded: @rpath/JSONJoy.framework/`

I understand it quite different from compiling on the simulator (linking against the frameworks) verse on the real machine. Could you help me on this?

Thanks @daltoniam

**Comment by pifer** [comment]
Hello! Im getting similar errors, even though I have added all the necessary libraries.
This happens both in my project and trying to run your SwiftPeople example:

> dyld: Library not loaded: @rpath/SwiftHTTP.framework/SwiftHTTP
> Referenced from: /Users/pablo/Library/Developer/CoreSimulator/Devices/F7B3AF8C-BA3B-4B6A-
> A549-DF8AC05C65CC/data/Containers/Bundle/Application/B6C9E464-1648-432A-B68B-
> DF46FB9C07BB/SwiftPeople.app/SwiftPeople
  Reason: image not found```

The only difference is I added the frameworks through Carthage, but I don't know if that should matter, since the were built with no issue. I'd appreciate any help I can get.

**Comment by bvsingh** [comment]
@pifer, have you checked the copy phase of your build? Maybe the framework is not copied. For running on device you need to code-sign the framework as well. It will error the same way when run on device without code-signing.

**Comment by daltoniam** [comment]
@bvsingh thanks.

**Comment by pifer** [comment]
Thanks!
