### ISSUE TITLE
CFNetwork SSLHandshake failed (-9805)

### ISSUE THREAD

**Issue by theblixguy** [daltoniam/SwiftHTTP#43]
I'm trying to HTTP POST (using Swift) to my server and I'm getting this error:

`2015-01-04 20:09:43.196 PIPiOS[1308:47829] CFNetwork SSLHandshake failed (-9805)
2015-01-04 20:09:43.197 PIPiOS[1308:47829] NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9805)`

Any idea what's going on? POST works fine otherwise (using Java or PHP)
Target: iOS8.1

**Comment by daltoniam** [comment]
Fairly generic error, but I do know SwiftHTTP works fine with HTTPS. Is the connection a self signed SSL certificate? I might try adding the self signed SSL code from the README. 

https://github.com/daltoniam/SwiftHTTP#authentication

Also if you are testing with the iOS Simulator try restarting it. I have seen weird network related issues with the simulator that require it to be restarted.

**Comment by theblixguy** [comment]
@daltoniam It's not self-signed, it's issued by COMODO. I've tried restarting the sim but the same issue persists. Is there no way to bypass SSL or enforce TLS1.0 or SSL3.0 ?

**Comment by theblixguy** [comment]
@acmacalister I tried using the self-signed method, but I still get

`2015-01-06 15:30:46.421 PIPiOS[956:20640] CFNetwork SSLHandshake failed (-9805)
2015-01-06 15:30:46.422 PIPiOS[956:20640] NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9805)`

I'm not sure how to use SecTrustEvaluate or something else since I'm just a beginner

**Comment by daltoniam** [comment]
@theblixguy interesting. Do you have any example code or domain in we can use to reproduce this?

**Comment by theblixguy** [comment]
@daltoniam Yes,

```swift
let randomUUID:String = NSUUID().UUIDString.stringByReplacingOccurrencesOfString("-", withString: "", options: NSStringCompareOptions.LiteralSearch, range: nil).lowercaseString
let username = usernameTextField.text
let password:String = passwordTextField.text
let parameters = ["succ": "wprin_menu.personal_page",
            "server":"4", "pid":randomUUID, "user":username, "password":password,
            "result":"OK"]

var request = HTTPTask()
        var attempted = false
        request.auth = {(challenge: NSURLAuthenticationChallenge) in
            if !attempted {
                attempted = true
                return NSURLCredential(forTrust: challenge.protectionSpace.serverTrust)
            }
            return nil
        }
        request.POST("https://kmis.brookes.ac.uk/csms/w_secure.login", parameters: parameters, success: {(response: HTTPResponse) in
            
            var alert = UIAlertController(title: "Success", message: "Login success", preferredStyle: UIAlertControllerStyle.Alert)
            alert.addAction(UIAlertAction(title: "Okay", style: UIAlertActionStyle.Default, handler: nil))
            self.presentViewController(alert, animated: true, completion: nil)
            
            },failure: {(error: NSError, response: HTTPResponse?) in
                
                var alert = UIAlertController(title: "Failure", message: "Login failure", preferredStyle: UIAlertControllerStyle.Alert)
                alert.addAction(UIAlertAction(title: "Okay", style: UIAlertActionStyle.Default, handler: nil))
                self.presentViewController(alert, animated: true, completion: nil)
                
        })
```

**Comment by daltoniam** [comment]
Sweet, that helps a lot, thanks.I am getting the same error. The underlining error return is kCFErrorDomainCFNetwork error -1200, which means the SSL connection failed for an unknown reason. My only guess is that might be because it is getting a 404 for the resource requested:
 
![screen shot 2015-01-06 at 8 45 20 am](https://cloud.githubusercontent.com/assets/905059/5632172/86fcb3a8-9581-11e4-91a7-e085c83de2fc.png)

Is this the expected behavior?

**Comment by theblixguy** [comment]
No, the URL is correct. If the login fails it redirects you to a Login failed page. Here's the equivalent Java code that I'm using for POSting and it works fine:

```java
public boolean LoginToPIP(String username, String password) {
        boolean status = false;
        httpClient = new DefaultHttpClient();
        String responseBody;
        httpPost = new HttpPost("https://kmis.brookes.ac.uk/csms/w_secure.login");
        List<NameValuePair> loginRequestPair = new ArrayList<NameValuePair>(6);
        loginRequestPair.add(new BasicNameValuePair("succ", "wprin_menu.personal_page"));
        loginRequestPair.add(new BasicNameValuePair("server", "4"));
        loginRequestPair.add(new BasicNameValuePair("pid", UUID.randomUUID().toString().replaceAll("-", "")));
        loginRequestPair.add(new BasicNameValuePair("user", username));
        loginRequestPair.add(new BasicNameValuePair("password", password));
        loginRequestPair.add(new BasicNameValuePair("action", "OK"));

        try {
            httpPost.setEntity(new UrlEncodedFormEntity(loginRequestPair));
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }

        try {
            HttpResponse response = httpClient.execute(httpPost);
            responseBody = EntityUtils.toString(response.getEntity());
            if (!responseBody.contains("Login Failed")) {
                status = true;
                doc = Jsoup.parse(responseBody);
            }

        } catch (ClientProtocolException cpe) {
            // Ignore
        } catch (IOException ioe) {
            // Ignore
        }
        return status;
    }
```

**Comment by theblixguy** [comment]
Okay, made a small mistake. In parameters, it should be `"action":"OK"` instead of `"result":"OK"` but it doesn't fix the issue

`
2015-01-06 22:42:39.525 PIPiOS[3856:207357] CFNetwork SSLHandshake failed (-9805)
2015-01-06 22:42:39.526 PIOiOS[3856:207357] NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9805)
`

I tried logging directly, like

`https://kmis.brookes.ac.uk/csms/w_secure.login?succ=wprin_menu.personal_page&server=4&pid=c3aa955f961a4db8b6ba4880890f00a2&user=myusername&password=mypassword&action=OK` and it worked, so yeah, the URL is correct.

**Comment by daltoniam** [comment]
hmmm interesting. Seems like it might be a bug in the SSL handling of NSURLSession. Not sure why it wouldn't like your SSL cert. I might recommend trying the code on real device. Also for the sake of testing, might want to try using a raw NSURLSession. I would wager the same error will come back.

**Comment by daltoniam** [comment]
I think we have narrowed this down to an environment issue or a bug in NSURLSession. I would recommend doing a simple NSURLSession example to reproduce the issue and open a bug on the apple radar.
