### ISSUE TITLE
How to save the cookie persistence

### ISSUE THREAD

**Issue by yaochangjun** [daltoniam/SwiftHTTP#45]
I have two button in test app, one is check the status of login and the second is login
1、I click the login button 
2、The login status is true When I click the check button
3、Close the application and open again
4、The login status is false When I click the check button
We use sessionid in cookies to check login status in server

**Comment by acmacalister** [comment]
If you want to persist an authentication, you would set the `NSURLCredential` persistence to the desired value. You can see more about that in the Apple Docs here.

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURLCredential_Class/index.html#//apple_ref/c/tdef/NSURLCredentialPersistence

If you are looking to manage cookies, you would use the `NSHTTPCookieStorage`. Docs for that are located here.

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSHTTPCookieStorage_Class/index.html
