### ISSUE TITLE
Does serializer support JSON key holding array?

### ISSUE THREAD

**Issue by larahub** [daltoniam/SwiftHTTP#48]
My JSON response has a key holding an array, is it possible that I can access its array elements only using SwiftHTTP?

**Comment by daltoniam** [comment]
The JSONResponseSerializer class simply converts the response data using NSJSONSerializtion, which returns a foundation object (Dictionary, Array, etc). If you want to convert the JSON to a swift object checkout:

https://github.com/daltoniam/JSONJoy-Swift
or
https://github.com/SwiftyJSON/SwiftyJSON
