### ISSUE TITLE
is support ios 7?

### ISSUE THREAD

**Issue by kuanglijun312** [daltoniam/SwiftHTTP#49]
is support ios 7?thank you!

**Comment by daltoniam** [comment]
It does, you just won't be able to use frameworks. I updated the README to make this more explicit.

https://github.com/daltoniam/SwiftHTTP#requirements

**Comment by kuanglijun312** [comment]
thank you

**Comment by daltoniam** [comment]
welcome. Thanks for pointing out the docs needed to be updated.
