### ISSUE TITLE
Problem with moveItemAtURL, when downloading Image 

### ISSUE THREAD

**Issue by kheinrich188** [daltoniam/SwiftHTTP#51]
Hey @ all, 

i have found an Issue, when you want to download an image from Webserver, and copy it from temp directory to documents directory: 

This is the line, that have to replace: 
let newPath = NSURL(string:  "\(paths[0])/\(response.suggestedFilename!)")!
with: 
NSURL(fileURLWithPath: "\(path)/\(fileName)")

because: 
You want to move pathURL but newPath is not a FILEPATH (file://....) 

So here is my code: 
```swift
if response.responseObject != nil {
     let filePath = response.responseObject as? NSURL
     if let url = filePath {
         if let path = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).first as? String {
             if let fileName = response.suggestedFilename {
                 if let newPath = NSURL(fileURLWithPath: "\(path)/\(fileName)") {
                     let fileManager = NSFileManager.defaultManager()
                     fileManager.removeItemAtURL(newPath, error: nil)
                     fileManager.moveItemAtURL(url, toURL: newPath, error:nil)
                 }
             }
         }
     }
 }
```

**Comment by daltoniam** [comment]
@kheinrich188 thanks. I updated the download example in the README to reflect this improvement.
