### ISSUE TITLE
Importing framework

### ISSUE THREAD

**Issue by mpclarkson** [daltoniam/SwiftHTTP#52]
Hi there

I'm new to Xcode and iOS so please bear with me. I don't seem to be able to import this into my iOS project. 

I have followed these steps in Xcode 6.1:
1. Downloaded and unzipped the the 0.9.2 release
2. Copied SwiftHTTP.xcodeproj into my project
3. Under Build Phases > Link Binary with Libraries I have selected SwiftHTTP.framework
4. Clicked the + and selected "New Copy Files Phase"
5. Renamed this to "Copy Framework" and added SwiftHTTP.framework
7. Set "Require Only App-Extension-Safe API" to Yes  under Build Settings
6. Added  "#import SwiftHttp" in my controller
7. Included a basic GET request task in the controller

The framework files are red.

When I compile I receive an "Apple Mach-O Linker Error":

```
Undefined symbols for architecture x86_64:
  "__TFC9SwiftHttp8HTTPTaskCfMS0_FT_S0_", referenced from:
      __TFC12HileniumAuth14ViewController11viewDidLoadfS0_FT_T_ in ViewController.o
  "__TMaC9SwiftHttp8HTTPTask", referenced from:
      __TFC12HileniumAuth14ViewController11viewDidLoadfS0_FT_T_ in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any help would be much appreciated.

Cheers
Matt

**Comment by acmacalister** [comment]
I tried your steps above in an example project and it worked just fine for me in the simulator. Generally the error above is caused when clang can not resolve the symbols properly, meaning the library is not getting linked for some reason. Does your build phases look like this?

![screen shot 2015-02-02 at 8 14 22 pm](https://cloud.githubusercontent.com/assets/1024755/6014422/6d6549b2-ab18-11e4-81e2-855603225953.png)

**Comment by mpclarkson** [comment]
I have just tried it again in a new project and I have the same error. My build phases screen looks the same as yours. What additional info can I give you?

**Comment by acmacalister** [comment]
Mmhh, If that is the same, then can you paste your code?

**Comment by acmacalister** [comment]
Or possibly zip the project up and throw it on dropbox, so I can download it and take a look?

**Comment by mpclarkson** [comment]
Here we go - a clean project with just a basic GET request in viewDidLoad: https://www.dropbox.com/s/gmqdytinyxfbpos/SwiftHttpTest.zip?dl=0

**Comment by mpclarkson** [comment]
PS I didn't do the "Copy Frameworks" steps as that didn't look like your screenshot

**Comment by acmacalister** [comment]
Ok, I got it building. A couple of things I noticed

- you need to change the module name from `SwiftHttp` to `SwiftHTTP`.
- The project you sent didn't have the SwiftHTTP project included, meaning no source to the build the framework. Is yours the same? Or rather is the `SwiftHTTP.xcodeproj` red in the project navigation? If so you need to make sure you drag it in there so our `SwiftHTTPTests.xcodeproj` knows where to find it.

Modified version below.

https://www.dropbox.com/s/vm0je8cxuamr7oi/SwiftHttpTest.zip?dl=0

**Comment by mpclarkson** [comment]
Oh sorry, as soon as I changed it to SwiftHTTP it worked. 

Any yes, the ```SwiftHTTP.xcodeproj``` is red.  I dragged the file into the project. Do I need to do something else?

Sorry, to waste your time on such an obvious error. :(

**Comment by acmacalister** [comment]
Awesome. Glad to hear that got it working. That is a bit strange. Can you do a drown drop of the `SwiftHTTP.xcodeproj` and see the source files associated with it? If those are still there and the framework is being properly linked in, you should be good to go. 

ah, no big deal. I'm just glad it was an easy fix. :smile:

**Comment by mpurusottamc** [comment]
Hi,

I am a newbie to Swift and iOS. I tried all the above steps to add SwiftHTTP using rogue. But, i am still getting the above error.

Any help would be much appreciated.

Thanks,
Puru

**Comment by nawar** [comment]
This is the easiest steps I managed to do :

1. Go to your xcode's "Source Control" and select "Checkout"
2. Once selected, checkout the repo
3. Xcode will open the repo project window
4. in the repo project window, Shift+Select all the files under the group
"SwiftHTTP" and drag them into your project, making sure to select "Copy
files if needed"
5. Start using the library directly without explicitly importing it.

**Comment by mpurusottamc** [comment]
Thanks. Selecting "Copy files if needed" helped.

Now, i am able to run the app without any errors.

**Comment by daltoniam** [comment]
@nawar thanks!

**Comment by imranbutt-java** [comment]
Hi acmacalister,
I got the error you have mentioned above in picture.
https://cloud.githubusercontent.com/assets/1024755/6014422/6d6549b2-ab18-11e4-81e2-855603225953.png
I even do "Copy files if needed" but it won't help and still remain red and it took sometime 3 to 4 hours.
Thanks.

**Comment by daltoniam** [comment]
You need to add SwiftHTTP as a target dependency to ensure it gets built. Also make sure if you are deploying to a real device to do:

https://github.com/daltoniam/SwiftHTTP#add-copy-frameworks-phase

**Comment by imranbutt-java** [comment]
Thanks Dalton, but the problem is resolved with following steps;
1- R-Click on project
2- Click on "Add Files to '<project_name>...'"
3- Select swiftHTTP.xcodeproj
4- Remember to check two options "Destination: Copy item if needed" and in "Added folders:" select "create groups" radio button.
Otherwise you simply get the folder reference.
Seems would help as it solved my problem.
