### ISSUE TITLE
Errors after 'import SwiftHTTP'

### ISSUE THREAD

**Issue by iSimar** [daltoniam/SwiftHTTP#53]
Just followed the installation instructions, opened myprojectname.xcworkspace, imported SwiftHTTP in one of the classes, got these errors.  Sorry I'm fairly new to iOS, swift and cocoapods. Thank you :smile: 

Here is a screenshot of all the errors:
https://www.dropbox.com/s/5k0zu7l50jdxt45/Screenshot%202015-02-03%2021.56.56.png?dl=0

**Comment by acmacalister** [comment]
It looks like you are running Xcode 5. You need to be running Xcode 6.1 and the cocoapods beta, to have proper Swift support.

**Comment by iSimar** [comment]
That was the problem, I updated my xcode and it worked. :+1:  Thank you!
