### ISSUE TITLE
swift 1.2

### ISSUE THREAD

**Issue by FabianTerhorst** [daltoniam/SwiftHTTP#55]
Hello,

i have tried today to run my project on the new xcode 6.3 beta with swift 1.2, but i have seen that your project isn´t compatible with this swift version. For example i have to replace: var opt = self.create(url, method:.DELETE, parameters: parameters,success,failure) with var opt = self.create(url, method: .GET, parameters: parameters, success: success, failure: failure).

**Comment by daltoniam** [comment]
I haven't got a chance to updated everything for Swift 1.2. I will try and get to that in the next few days. I will create a Swift 1.2 branch that can be used until it is out of beta.

**Comment by FabianTerhorst** [comment]
ok, thanks for your fast reply

**Comment by daltoniam** [comment]
Alright, I think I got it updated. Check out the swift-1.2 branch and let me know if that works.

**Comment by FabianTerhorst** [comment]
Now everything works very well, thanks

**Comment by daltoniam** [comment]
:+1:  great, glad to hear it.
