### ISSUE TITLE
get a array of json objects...

### ISSUE THREAD

**Issue by reshadf** [daltoniam/SwiftHTTP#56]
Hi I want to use swifthttp to get a array of returned json objects... Is this possible? I can't find a way to achieve this.. Here is what I got.. 

    func requestAllCars() {
        var request = HTTPTask()
        let params: Dictionary<String, String> = ["apikey":apikey, "username":username]
        request.requestSerializer = JSONRequestSerializer()
        request.responseSerializer = JSONResponseSerializer()
        request.POST(url, parameters: params, success: {(response: HTTPResponse) in
            if let dict = response.responseObject as? Dictionary<String, String> {
                println("print the whole response: \(dict)")
                if let statusCode: AnyObject = dict["status"] {
                    if statusCode as NSString == "Error" {
                        // Oops error
         
                        })
                    }
                } else {
                    

                }
            }
            }, failure: {(error: NSError, response: HTTPResponse?) in
                println("object not received \(error)")
               
                })
        })

    }

**Comment by daltoniam** [comment]
See this: http://vluxe.io/jsonjoy.html. It has an example on how to achieve this.
