### ISSUE TITLE
Posting multipart/form-data seems to be broken

### ISSUE THREAD

**Issue by msamoylov** [daltoniam/SwiftHTTP#57]
Hi.

I'm trying to reproduce my Go code https://github.com/msamoylov/insuranceutil/blob/master/main.go in Swift and it doesn't seem to work. I keep getting an error message saying that 'personal code' field wasn't sent.

My implementation is https://gist.github.com/msamoylov/5152ed92456fd557b540

Any ideas? Thanks.

**Comment by acmacalister** [comment]
You are having an issue with trying to return a value from an async closure. This is different from Go's http request which is synchronous vs SwiftHTTP which is asynchronous. see issue #30 and #42 or http://vluxe.io/swifthttp.html for more info on how to design your code asynchronously.

**Comment by msamoylov** [comment]
That wasn't obvious. Thanks!
