### ISSUE TITLE
Archiving an app fails

### ISSUE THREAD

**Issue by anthonycastelli** [daltoniam/SwiftHTTP#58]
I'm trying to archive my app to submit to ITC for review. When I try and Archive, I get an error `Could not build Objective-C module 'SwiftHTTP'` I've cleared out my DerivedData and everything I can think of. Is there something wrong with this framework or am I just missing a step?

**Comment by daltoniam** [comment]
I am not aware of any issues with the framework. Did you copy the framework into the bundle? When submitting or running on a physical device, you have to copy the framework into the build. See this for more info: 
https://github.com/daltoniam/SwiftHTTP#add-copy-frameworks-phase

**Comment by anthonycastelli** [comment]
Apparently Xcode decided to remove it from that Phase. Don't know how I missed that before. Thanks!

**Comment by daltoniam** [comment]
:+1:  Can't trust xCode as often as it crashes :smile:
