### ISSUE TITLE
Unable to build project in XCode 6.1.1

### ISSUE THREAD

**Issue by bumblebeeman** [daltoniam/SwiftHTTP#60]
I get the following error when I try and build a fresh project in XCode 6.1.1 after adding this library via CocoaPods.

Anybody experienced this before and know what the deal is?

https://imgur.com/oaLSsfC

Cheers

**Comment by daltoniam** [comment]
I haven't experienced this issue with my test pod project, are you running the cocoapods beta? 

If you're not running the beta, use `gem install cocoapods --pre` to upgrade to the beta (it is a beta, so use at your own risk :smile: ).

**Comment by bumblebeeman** [comment]
Yeah you can close this, figured it out.

Basically installed the non beta version first, then installed the beta and it didn't install (so I was still on v35 of CocoaPods).

Ran the uninstall gem command and it didn't install, ran the command to install the beta and it didn't work! pod was still there and reporting version v35, even after a restart.

Ended up having to delete the gem directory and things started to work again

Bit of the PITA but cooking with gas now, thanks :)

**Comment by bumblebeeman** [comment]
Quick question though, can I target iOS 7 with this library? I recognise that's pushing it a bit!

**Comment by daltoniam** [comment]
ah ruby gems, got to love'em :smile:. Glad you got it sorted out.

**Comment by daltoniam** [comment]
Yes it can, but has to be source only, not sure cocoa pods will support that :confused:

**Comment by bumblebeeman** [comment]
Good to know, thanks very much! Awesome library by the way :)

**Comment by daltoniam** [comment]
:+1: Thanks!
