### ISSUE TITLE
Cannot uploading a file

### ISSUE THREAD

**Issue by lobodart** [daltoniam/SwiftHTTP#61]
Please, implement the file upload as soon as possible ! I (we) need it in this awesome library ! :D

**Comment by daltoniam** [comment]
Do you mean the background file uploading? I know I have comment in there about needing to implement the file upload, but that is specifically for the background file uploads only. Standard file uploads should work fine with the `HTTPUpload` object. I hope to get the time to do the background file uploading soon.

**Comment by lobodart** [comment]
Oh ok sorry. Yeah I mean standard file upload. I ask you the question because in your Readme, the part "Upload" is "empty". I'm going to see how `HTTPUpload` works :smile: Thanks for your answer !

**Comment by daltoniam** [comment]
It is all good. I agree, it is confusing :smile:. I will update the README to make this clearer.
