### ISSUE TITLE
Download retry

### ISSUE THREAD

**Issue by nawar** [daltoniam/SwiftHTTP#62]
Awesome job with the wrapper :+1: 
Just wondering if there would be any attempt in the future to support *retried* downloads for the `download` call like this

    request.download(url: String, 
    retries: Int /* number of retries */
    parameters: Dictionary<String,AnyObject>?,
    progress:((Double) -> Void)!, 
    success:((HTTPResponse) -> Void)!, 
    failure:((NSError, HTTPResponse?) -> Void)!)

It's useful to retry from the original call rather than calling the `request.download` from within the `failure closure`. May be there's a better way to do it :)

**Comment by daltoniam** [comment]
Thank you. I haven't thought of that, but I could see how it could be useful. I might propose another way to retry logic using recursion and closures:

```swift
func getFile(url: String, attempt: Int, success:((HTTPResponse) -> Void), failure:((NSError, HTTPResponse?) -> Void)) {
	var request = HTTPTask()
	let downloadTask = request.download(url, parameters: nil, progress: {(complete: Double) in
	    println("percent complete: \(complete)")
	    }, success: {(response: HTTPResponse) in
	    	success(response) //download was successful
	    } ,failure: {(error: NSError, response: HTTPResponse?) in
			if attempt < maxAttempts { //maxAttempts could be your desired number of retries, 5, 10, etc
				getFile(url, attempt+1,success, failure) //try again...
			} else {
				failure(error, response)
			}
	})
}

//now run it:
getFile("http://vluxe.io/assets/images/logo.png",0, success: {(response: HTTPResponse) in
	//do stuff with the download...
} ,failure: {(error: NSError, response: HTTPResponse?) in
	//sadness
})
```

I just threw this together, so not sure on total syntax accuracy, but the general idea should make sense. I would say this gives quite a bit of flexibility in the implementation and does require any changes at all :smile: .

**Comment by nawar** [comment]
That would work for now, thanks for the insight :)

**Comment by daltoniam** [comment]
:+1:
