### ISSUE TITLE
Multiple file downloads

### ISSUE THREAD

**Issue by nawar** [daltoniam/SwiftHTTP#63]
I was tinkering with the library and I wanted to share, off the top of my head, my own implementation of multiple file downloads using multiple `downloadTasks` with the same background Session. Not sure if this is kosher though.

    public func downloadMultiple(urls: Array<String>, parameters: Dictionary<String,AnyObject>?,progress:((Double) -> Void)!, success:((HTTPResponse) -> Void)!, failure:((NSError, HTTPResponse?) -> Void)!) -> [String:NSURLSessionDownloadTask?] {
        
        var tasks = Dictionary<String,NSURLSessionDownloadTask>()
        let ident = createBackgroundIdent()
        let config = NSURLSessionConfiguration.backgroundSessionConfigurationWithIdentifier(ident)
        let session = NSURLSession(configuration: config, delegate: self, delegateQueue: nil)
        
        for url in urls {
            
            let serialReq = createRequest(url,method: .GET, parameters: parameters)
            if serialReq.error != nil {
                failure(serialReq.error!, nil)
                tasks[url] = nil
             }
            
            let task = session.downloadTaskWithRequest(serialReq.request)
            let taskId = ident + "-" + String(task.taskIdentifier)
            self.backgroundTaskMap[taskId] = BackgroundBlocks(success,failure,progress)
            task.resume()
            tasks[url] = task
        }
        
        return tasks
    }

Let me know what you think. I can put that into a pull request.

**Comment by daltoniam** [comment]
That is a slick idea, my only concern is that I believe the background identifier has to be unique per download session to be able to identify the request on relaunch.

https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLSessionConfiguration_class/#//apple_ref/occ/clm/NSURLSessionConfiguration/backgroundSessionConfigurationWithIdentifier:

**Comment by nawar** [comment]
I checked the call to `createBackgroundIdent` which I used above and from the code base (see below) and it looks like it is creating a decent unique identifier. For the `tasks[String, NSURLSessionDownloadTask ]` dictionary I am just using it as a reference for the caller code to do whatever it needs with the returned task, inspired by your original code for `download`. 
I'll need to test the call backs thoroughly though, I saw some issues with my code when dealing with that. 

    private func createBackgroundIdent() -> String {
        let letters = "abcdefghijklmnopqurstuvwxyz"
        var str = ""
        for var i = 0; i < 14; i++ {
            let start = Int(arc4random() % 14)
            str.append(letters[advance(letters.startIndex,start)])
        }
        return "com.vluxe.swifthttp.request.\(str)"
    }

**Comment by daltoniam** [comment]
haha, failure on my part. I even wrote that method :smile:. Alright cool, once you have something you like, let me know :+1:

**Comment by javierC1988** [comment]
Hi, Im new in this, I'm wotking with Swift HTTP and JSONJoy 
Everything is OK and compile and upload to simulator, but when I call webservice I have an error on JSONJoy.framework, it says no image found
Please can you help me
