### ISSUE TITLE
Integration with JSONJoy

### ISSUE THREAD

**Issue by javierC1988** [daltoniam/SwiftHTTP#65]
Hi, Im new in this, I'm wotking with Swift HTTP and JSONJoy
Everything is OK and compile and upload to simulator, but when I call webservice I have an error on JSONJoy.framework, it says no image found
Please can you help me

**Comment by daltoniam** [comment]
Are you trying to deploy to a real device and it's working? Check this out:

https://github.com/daltoniam/JSONJoy-Swift#add-copy-frameworks-phase

**Comment by javierC1988** [comment]
not yet, i'm trying in the simulator

**Comment by daltoniam** [comment]
Alright. I will need a code example and a screenshot of your settings to help further. As long as you followed the install docs for both SwiftHTTP and JSONJoy it should work fine.

**Comment by javierC1988** [comment]
I changed my install of JSONJoy for cocoapods, this is my error.

![error1cocoa](https://cloud.githubusercontent.com/assets/9955461/6536474/e844777c-c41b-11e4-95e4-97803ffd7206.png)
![error2cocoa](https://cloud.githubusercontent.com/assets/9955461/6536475/e847bbbc-c41b-11e4-8282-52115b5d55a3.png)

**Comment by daltoniam** [comment]
Ok cool. Did you install the CocoaPods beta? If not, use `gem install cocoapods --pre`.  

Also are you building with the yourproject.xcworkspace file or yourproject.xcodeproj file? You should be using the xcworkspace.

**Comment by javierC1988** [comment]
the first thing is done, but second one I cannot understand you I havent used that file

**Comment by daltoniam** [comment]
CocoaPods creates a workspace project file that you should be using, instead of the original xcodeproj file. 

http://cocoapods.org under the "Get Started" tab.

![screen shot 2015-03-06 at 1 20 43 pm](https://cloud.githubusercontent.com/assets/905059/6536589/a6043892-c403-11e4-91f9-66e24b31279f.png)

**Comment by javierC1988** [comment]
I openned it, but thats my screen capture
![errorcocoa3](https://cloud.githubusercontent.com/assets/9955461/6536616/292eaf36-c41d-11e4-9c79-80dd49f9f2f2.png)

**Comment by daltoniam** [comment]
There a couple issues here, but first you need to close the project file and the workspace file. Then just open the workspace file. Try building after that.

**Comment by javierC1988** [comment]
Ok, it built and run, now Im getting this error
Could not build Objective-C module 'JSONJoy'

**Comment by daltoniam** [comment]
You need to clean the build folder. Hold option and go to product-> clean inside xCode. See this for more info:
http://stackoverflow.com/questions/26834293/swift-could-not-build-objective-c-module-alamofire

**Comment by javierC1988** [comment]
Thanks a lot for being patient with me.
I solved JSON Joy
But I've done the same to SwiftHTTP but issue persist
Could not build Objective-C module 'SwiftHTTP'

**Comment by javierC1988** [comment]
solved!! sorry man and thanks a lot again great Pro!!

**Comment by daltoniam** [comment]
:+1: nice work. Welcome and enjoy.
