### ISSUE TITLE
SwiftHTTP.framework is not shown in the Add framework dialog

### ISSUE THREAD

**Issue by VolvoOlympian** [daltoniam/SwiftHTTP#66]
From the SwiftHTTP documentation:
"Add the SwiftHTTP.xcodeproj to your Xcode project. Once that is complete, in your "Build Phases" add the SwiftHTTP.framework to your "Link Binary with Libraries" phase."

I only see the SwiftHTTPOSX.framework in the add framework dialog box, but not the SwiftHTTP.framework. The thing is I am developing an app for iOS...

I guess I may have done something wrong? What is the correct way to add the SwiftHTTP.xcodeproj to my iOS xCode project? Sorry I am new to this...

**Comment by daltoniam** [comment]
Can you provide a screenshot of your current xCode project configuration? It should look something like this:

![screen shot 2015-03-12 at 7 56 12 am](https://cloud.githubusercontent.com/assets/905059/6620332/51b2bbb8-c88d-11e4-9f29-fd7194f2df96.png)

**Comment by daltoniam** [comment]
@VolvoOlympian did you get this sorted out?

**Comment by VolvoOlympian** [comment]
Sorry for the delay over the weekend, I got it sorted by re-importing the SwiftHTTP project.

**Comment by daltoniam** [comment]
Excellent and nice work.
