### ISSUE TITLE
Please help!! POST JSON

### ISSUE THREAD

**Issue by javierC1988** [daltoniam/SwiftHTTP#67]
Hi Dalton, cant perform a post action, it retrieves me error 415

this is my code
![postjson](https://cloud.githubusercontent.com/assets/9955461/6652772/533bf73a-ca48-11e4-8eec-becbf30d3e63.png)

**Comment by javierC1988** [comment]
I've updated the code with this two lines
        request.requestSerializer = JSONRequestSerializer()
        request.responseSerializer = JSONResponseSerializer()

Now I get this error
![errorpost](https://cloud.githubusercontent.com/assets/9955461/6652797/7d856692-ca49-11e4-97a1-f9b1d883ef5e.png)

**Comment by javierC1988** [comment]
Sorry solved, remove 
request.responseSerializer = JSONResponseSerializer()
was the solution

**Comment by daltoniam** [comment]
Good work, nicely done.
