### ISSUE TITLE
Waiting for data to be fetched

### ISSUE THREAD

**Issue by reshadf** [daltoniam/SwiftHTTP#71]
Hello, Is there a way to wait for the data to be fetched before showing the ViewController? Or do a sync instead of async?

**Comment by acmacalister** [comment]
Not really. SwiftHTTP uses NSURLSession under the hood, which does not provide synchronous APIs by default. [This SO article](http://stackoverflow.com/questions/21198404/nsurlsession-with-nsblockoperation-and-queues) has how you could achieve a synchronous request using an NSOperationQueue, which SwiftHTTP supports, but as the accepted answer points out on the SO question, I would strongly suggest you use an async pattern. You could either fetch the data first then push over to your new view controller or just use a loading dialog, while you wait for the data from the network...
