### ISSUE TITLE
how to refresh UITableView after http request

### ISSUE THREAD

**Issue by learningpro** [daltoniam/SwiftHTTP#72]
When should I call UITableView.reloadData , if I want to refresh the tableview after the http request? Because the time http request costs is not a const, so I cannot refresh tableview exactly after the request function. Thank you very much

**Comment by mpurusottamc** [comment]
You should write it in the success handler.

Also, since the success handler is a closure, use self.tableView.reloadData().

**Comment by learningpro** [comment]
@mpurusottamc  thank you for your so quick answer! But my problem is I wrote http request in a class, and the uitableview is in another class, so I cannot write it in the success handler now  T_T

**Comment by mpurusottamc** [comment]
Here is one way of solving the problem :
Step 1 : Define a protocol

    protocol TableViewProtocol {
        func didReceiveTableData(result: [AnyObject]?)
    }

Step 2 : Create a delegate in the class where you have the HTTPTask Get request and call the delegate with response once you receive the response from the GET request

    class APICaller {
    var tableViewDelegate: TableViewProtocol?
    
    func getDataFromAPI() {
        var request = HTTPTask()
        request.GET("<URL>", parameters: params, success: {(response: HTTPResponse) in
            if response.responseObject != nil {
                var resp = response.responseObject
                // do the deserialization from resp variable here and assign it to results variable

                // call the delegate
                self.tableViewDelegate?.didReceiveTableData(results)
            }
            },failure: {(error: NSError, response: HTTPResponse?) in
                println("error: \(error)")
        })
    }
    }

Step 2 : implement the protocol in the class where you have the UITableView

    class HomeViewController: UIViewController, TableViewProtocol {
    var result: [AnyObject]?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        var api: APICaller = APICaller()
        api.tableViewDelegate = self
        
        // Get data for the UITableView
        api.getDataFromAPI()
    }
    
    func didReceiveTableData(result: [AnyObject]?) {
        if let act = result {
            dispatch_async(dispatch_get_main_queue(), {
                self.result = act
                self.tableView.reloadData()
            })
        } else {
            // Handle error here
        }
    }    
    }

Hope this gives you the idea.

**Comment by daltoniam** [comment]
@mpurusottamc excellent explanation and thanks!

**Comment by learningpro** [comment]
@mpurusottamc  Thank you very much!
