### ISSUE TITLE
Json serializer return nil

### ISSUE THREAD

**Issue by antares38** [daltoniam/SwiftHTTP#74]
Hi,

here is my problem, with the last version in swift 1.2 I got the cast that failed if I am using a JSONResponseSerializer.

Here is my code :

```swift
var ipRequest = HTTPTask()
ipRequest.requestSerializer = JSONRequestSerializer()
ipRequest.responseSerializer = JSONResponseSerializer()

ipRequest.GET("https://www.meethue.com/api/nupnp", parameters: nil, success: {(response: HTTPResponse) in
    println("Get Ok")
    if let dict = response.responseObject as? Dictionary<String,AnyObject> {
        println("OK !")
    }
    },failure: {(error: NSError, response: HTTPResponse?) in
        println("error: \(error)")
})
```

**Comment by antares38** [comment]
So I find what was my mistake and it was because my json was a json array, something like : 
[{}]
in that case you need to use 

if let array = response.responseObject as? Array<AnyObject> {
                println("Cast array ok")
                if let dict = array[0] as? Dictionary<String, AnyObject> {
                    println(dict["internalipaddress"])
                }

 Bests !

**Comment by daltoniam** [comment]
Nicely done :+1:
