### ISSUE TITLE
Unable of creating custom HTTPRequestSerializer

### ISSUE THREAD

**Issue by LeoUnglaub** [daltoniam/SwiftHTTP#75]
Hey,
i have added SwiftHTTP to my project via adding it to `Link Binary with Libraries`. When i am trying to create custom HTTPRequestSerializer i get some compiling error. When i add my custom HTTPRequestSerializer into your HTTPRequestSerializer.swift it works fine, but when i want to add it into its own class in my project i get the following error:

```
import UIKit
import SwiftHTTP

public class MyRequestSerializer: HTTPRequestSerializer
{
	public override func createRequest(url: NSURL, method: HTTPMethod, parameters: Dictionary<String, AnyObject>?) -> (request: NSURLRequest, error: NSError?)
	{
	}
}


Error: Method does not override any method from its superclass.
```

Any ideas why?
thanks and greetings
Leo

**Comment by daltoniam** [comment]
It appears I forgot to make the visibility of the `createRequest` method public, just checked in a fix. Thanks!

**Comment by LeoUnglaub** [comment]
Hey,
thanks for the quick response. It works, but i cannot access any other methods like `isURIParam` because they are also not available. Maybe you could change the access modifiers to something that allows me to use them as well.

Thanks and greetings from Vienna
Leo

**Comment by daltoniam** [comment]
Ah, yeah I could see that being useful. I make the `isURIParam` and `isMultiForm` public. The others seems specific to the HTTP serializer, but let me know if you need access to any of the other ones.

**Comment by LeoUnglaub** [comment]
Yeah, thanks a lot!
