### ISSUE TITLE
Weird bug with Xcode 6.3

### ISSUE THREAD

**Issue by msamoylov** [daltoniam/SwiftHTTP#76]
It worked before upgrading to Xcode 6.3, any ideas? 

    $ carthage bootstrap
    *** No Cartfile.resolved found, updating dependencies
    *** Fetching SwiftHTTP
    *** Checking out SwiftHTTP at "0.9.3"
    *** xcodebuild output can be found in /var/folders/pl/kgk3xb2x4yj1mbdkjxtsj8n80000gn/T/carthage-xcodebuild.ErWB2R.log
    *** Building scheme "SwiftHTTP" in SwiftHTTP.xcodeproj
    *** Building scheme "SwiftHTTPOSX" in SwiftHTTP.xcodeproj
    ** BUILD FAILED **

    The following build commands failed:
        CompileSwift normal x86_64 /Users/mike/Projects/monmar/insurancechecker/Carthage/Checkouts/SwiftHTTP/Tests/SwiftHTTPTests.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    (2 failures)

Build log: https://gist.github.com/msamoylov/9bcaecc4a623e7f89ebb

**Comment by daltoniam** [comment]
I just checked into master what might be a fixed. I removed the `SwiftHTTPOSX` framework name and unified them to just SwiftHTTP. I forgot to update the tests thought :smile:

**Comment by daltoniam** [comment]
Where you to check if the latest checkin resolved the issue?

**Comment by daltoniam** [comment]
I added a new tag `0.9.4` which will probably fix the issue.
