### ISSUE TITLE
Adding a debug mode

### ISSUE THREAD

**Issue by LeoUnglaub** [daltoniam/SwiftHTTP#77]
Hey,
it would be very usefull if you could add a debug mode. By that i mean a mode that logs all requests and responses to the command line. This would be very helpful during debugging when you have to check exactly why a json response is broken or why the body is empty.

I think it would be great if you could add this for requests and responds so optionally everything gets logged to the command line.

thanks and greetings from vienna
Leo

**Comment by daltoniam** [comment]
Ok, I will consider it. Normally I just use `println` function in the success and failure closures to query the response values. Also you you can use `HTTPResponse` text method to print the string value of the data.

https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L42

**Comment by LeoUnglaub** [comment]
Hey,
yeah thats the way i do it currently. However if you want the url, the response headers and the request payload you have to do a lot of writing. I think in this case simply using myrequest.debug = true would be much simpler.

Example debug output:
```
URL: 
https://github.com

Header:
HTTP/1.1 200 OK
Server: GitHub.com
Date: Wed, 15 Apr 2015 10:22:51 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Status: 200 OK

Payload:
<!DOCTYPE html>
```

Greetings
Leo

**Comment by daltoniam** [comment]
good point. I think we might add it as a method on the `HTTPResponse` object, seems to make sense there.

**Comment by daltoniam** [comment]
I added this as a `description` property the `HTTPResponse` object.

Example:
```swift
var request = HTTPTask()
request.GET("http://vluxe.io", parameters: nil, success: {(response: HTTPResponse) in
    println("\(response.description)")
    },failure: {(error: NSError, response: HTTPResponse?) in
        println("error: \(error)")
})
```
This will print out much the same as the format you had above.

**Comment by LeoUnglaub** [comment]
Hey,
it works very well. Thanks for adding it.

Greetigs
Leo

**Comment by LeoUnglaub** [comment]
Hey,
i just noticed that this only works if the request succeesed. In the failure closure it does not work. But i think it should work there as well because you could get an "error" like 404 or so and still a valid http response.

Greetings
Leo

**Comment by daltoniam** [comment]
Yeah that could be because the `HTTPResponse` is nil. I just added the status code to the description print out and made the `HTTPResponse` show up in more of the failure closures cases. I think that should take care of it.
