### ISSUE TITLE
[solved]Very slow response

### ISSUE THREAD

**Issue by dgaleazzo** [daltoniam/SwiftHTTP#81]
Hi mate, thanks for your work! I'm running in very slow response, for example calling: 
```swift
private func test() {
        request.GET("http://www.google.it", parameters: nil, success: {(response: HTTPResponse) in
                if let jsonArray = response.responseObject as? NSData {
                    self.downloadedImageView.image = self.capturedImageView.image
                }
            },failure: {(error: NSError, response: HTTPResponse?) in
                println("error: \(error)")
        })
    }
```
if I breakpoint to "self.downloadedImageView.image = self.capturedImageView.image" row, from resume to the image assign elapse like 3/4 seconds.

With:

```swift
dispatch_async(dispatch_get_main_queue()) {
        self.downloadedImageView.image = self.capturedImageView.image
}
```
All works instantly. Thanks

**Comment by daltoniam** [comment]
Yeah that is expected behavior. The success block returns on a background thread to support JSON parsing and then calling `dispatch_async(dispatch_get_main_queue()){}` for UI needs. I will update the docs to better reflect this.

**Comment by dgaleazzo** [comment]
Yes, UIKit stuffs need to run into main thread. Update docs sounds so good, thanks again for work.

**Comment by daltoniam** [comment]
https://github.com/daltoniam/SwiftHTTP#ui-changes
