### ISSUE TITLE
Problem after upgrading xcode (6.3)

### ISSUE THREAD

**Issue by pltech** [daltoniam/SwiftHTTP#82]
Hello,

I am getting this error when i want to run app on my iphone

dyld: Library not loaded: @rpath/SwiftHTTP.framework/SwiftHTTP
  Referenced from: /private/var/mobile/Containers/Bundle/Application/42046EBB-DDED-4838-BA51-79601629B1F0/Powerlabel.app/Powerlabel
  Reason: image not found

**Comment by pltech** [comment]
Sorry fixed it.

**Comment by tpcmedia** [comment]
hi utku dalmaz how dit you fixed it ?
