### ISSUE TITLE
Support for easy certificate pinning

### ISSUE THREAD

**Issue by LeoUnglaub** [daltoniam/SwiftHTTP#86]
Hey,
certificate pinning has become more and more important. But sadly it's still very complicated to do in IOS. So i was hoping you would like to implement a simple abstraction around cert pinning in SwiftHTTP.

What are your thoughts on the topic?
Thanks and greetings
Leo

**Comment by daltoniam** [comment]
I would like to see SSL pinning added to SwiftHTTP. I personally haven't had the time to research and implement a solution yet, so Pull Requests are welcomed.

**Comment by LeoUnglaub** [comment]
Hahaha, i can give it a shot but i actually was asking you for the feature because i failed in my first trail *g* It's so complicated to get right, i actually think Apple does not want it's users to pin there certs. But i will give it a try in the next few days.

**Comment by daltoniam** [comment]
ah, ok, makes sense, no worries then :smile:. I want to look into it in the near future so if nothing comes together in the next few days, I will start working on it soon.

**Comment by LeoUnglaub** [comment]
There are actually a lot of things to keep in mind while doing it. Some implementations just include the fingerprint of the cert and then check it. Some people embedd the entire cert and then fingerprint it on the fly.

Another thing to keep in mind is if you allow to pin multiple certs. Because if you pin one cert and it expires it would render all non-updated apps broken. Just because they have not had time to install the update yet. So maybe it should be possible to pin multiple certs so if i know my cert expires in 3 months i deploy and update containing the upcoming cert and the current one.

Thats just a few things i thought about while trying to implement it.
Greetings
Leo

**Comment by htarwara6245** [comment]
@daltoniam,I am really appreciated to use this Library.It was perfect Lib and easy to use.If you dont mind,can u do the support for HTTPS?Thank you.I am also newbie to Swift,too.

**Comment by daltoniam** [comment]
@LeoUnglaub thanks for the notes, I will keep that in mind. @htarwara6245 I hear ya, I will get the SSL pinning done as time permits.

**Comment by sdaduanbilei** [comment]
![image](https://cloud.githubusercontent.com/assets/3861614/7603394/ff681c50-f964-11e4-830d-6d50e6f97432.png)

**Comment by daltoniam** [comment]
Alright folks, I have something checked into the master branch for SSL pinning. I don't have a easy way to test it, so I am hoping y'all can help me out :smile:. 

https://github.com/daltoniam/SwiftHTTP#ssl-pinning

I haven't created the `0.9.5` yet, as I want to much sure this works first. Please test from the master branch and then we can create the stable `0.9.5` once we are happy.

**Comment by LeoUnglaub** [comment]
Hey,
i was trying the current version in my project but do to some other change in the failure callback i was unable of compiling it. But the cert pinning parts looks good as far as i can tell.

I am going to report back as soon as i have figured out the other issue.
Thanks and greetings
Leo

**Comment by daltoniam** [comment]
tag `0.9.5` released!
