### ISSUE TITLE
Passing NSNumber array parameter throws exception

### ISSUE THREAD

**Issue by xplatsolutions** [daltoniam/SwiftHTTP#88]
Hi,

Passing NSDictionary parameters like this:

NSDictionary* params =
        @{
        @"deviceId": [WEESettings uuid],
        @"location": @[ [NSNumber numberWithDouble:coordinates.latitude], [NSNumber numberWithDouble:coordinates.longitude] ]
        };

It throws an exception in this method

- (NSString*) stringValue
    {
    NSString* val = [self getValue];
    if (!self.key)
        {
        return [HTTPHelper uriEncoded:val];
        }
    return [NSString stringWithFormat:@"%@=%@", [HTTPHelper uriEncoded:self.key], [HTTPHelper uriEncoded:val]]; // Exception here.
    }

So it's the [HTTPHelper uriEncoded:self.key] as it seems.

-[__NSCFNumber length]: unrecognized selector sent to instance 0x174030740
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber length]: unrecognized selector sent to instance 

Any Idea?

**Comment by daltoniam** [comment]
I'm not sure what code you are referencing, might be looking for a different repository. SwiftHTTP doesn't have an `HTTPHelper` object or a `uriEncoded:` method and is in Swift and not Objective-C.

**Comment by xplatsolutions** [comment]
Sorry, wrong place, it was from hurrying...

**Comment by daltoniam** [comment]
All good, I assumed that was the case :smile:
