### ISSUE TITLE
copy request occrus error

### ISSUE THREAD

**Issue by jinsust** [daltoniam/SwiftHTTP#89]
I use operationQueue and save the request as SwiftHTTP.HTTPOperation

then I get  another HTTPOperation Object from copy method

when I try add the new Object into queue, the error happen

It seems like that HTTPOperation not implement copy method. What should I do?

There is code:
let operationQueue = NSOperationQueue()
var request = HttpTask()
var opt = request.create(...........)
if let o = opt {
    operationQueue.addOperation(o)
}
........
// I just want to send the same req twice 
if let o = opt.copy() {  
// here will occrus error  --  'NSInvalidArgumentException', reason: '-[SwiftHTTP.HTTPOperation //copyWithZone:]: unrecognized selector sent to instance
   opreationQueue.addOperation(o)  
}

**Comment by daltoniam** [comment]
That makes sense, the `HTTPOperation` class doesn't implement the copy protocol. You could run the request twice by:
```swift
var opt2 = request.create(...........) //request is the same HTTPTask as before, just another call to create
if let o = opt2 {
operationQueue.addOperation(o)
}
```
