### ISSUE TITLE
URL containing spaces!

### ISSUE THREAD

**Issue by JV17** [daltoniam/SwiftHTTP#91]
I think you should allow requests where the url contains spaces.. In my case I did this within your `createRequest` function..

I have added this to the url string
```
urlVal.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!
```
resulting of,
```
private func createRequest(url: String, method: HTTPMethod, parameters: Dictionary<String,AnyObject>!) -> (request: NSURLRequest, error: NSError?) {
        var urlVal = url
        //probably should change the 'http' to something more generic
        if !url.hasPrefix("http") && self.baseURL != nil {
            var split = url.hasPrefix("/") ? "" : "/"
            urlVal = "\(self.baseURL!)\(split)\(url)"
        }
    if let u = NSURL(string: urlVal.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!) {
        return self.requestSerializer.createRequest(u, method: method, parameters: parameters)
    }
    return (NSURLRequest(),createError(-1001))
    }
```

**Comment by acmacalister** [comment]
We already encode, url params and such. URL hostnames can't have spaces according to the RFC, so I don't think we need to need to encode them, as that is not a valid url. You can check out the RFC here:

http://tools.ietf.org/html/rfc1123#section-2
http://tools.ietf.org/html/rfc952

Do you have a use case you are running into with a url that has those invalid characters?

**Comment by JV17** [comment]
Yes, I was doing some calls to a weather api and passing the city like Las Vegas without the encoding for the space it was generating an http request error from the framework end not the server/api.. And the server for some reason doesn't like the city without the spaces in it :/

The solution for the problem was the one I have posted above.. Not sure what you would like to do with the ticket at least for other people who might come across with a similar issue, it might be helpful for them later on..

**Comment by daltoniam** [comment]
Are you sending the city of Las Vegas like `http://someurl.com?city=Las Vegas`? Or more specifically:

```swift
var request = HTTPTask()
request.GET("http://someurl.com?city=Las Vegas", parameters: nil, success: {(response: HTTPResponse) in
//do stuff with response
},failure: {(error: NSError, response: HTTPResponse?) in
    println("error: \(error)")
})
```

If so, that explains the issue. You need to change it to where the parameters are sent in the parameters field like so:

```swift
var request = HTTPTask()
request.GET("http://someurl.com", parameters: ["city": "Las Vegas"], success: {(response: HTTPResponse) in
//do stuff with response
},failure: {(error: NSError, response: HTTPResponse?) in
    println("error: \(error)")
})
```

The values in the parameters field automatically get append for the proper HTTPMethod (it adds the ?city=Las%20Vegas for you).

**Comment by JV17** [comment]
Thanks @daltoniam, indeed I was appending the `parameters` to the url myself.. lol.. I am so sorry for this one!!

**Comment by daltoniam** [comment]
All good, glad we got it figured out :smile:.
