### ISSUE TITLE
Upload progress in %

### ISSUE THREAD

**Issue by Mauricevb** [daltoniam/SwiftHTTP#94]
Is it possible to get or calculate the progress in percentage? That should be very handy for uploads.
Thank you very much btw for this lib :)

**Comment by daltoniam** [comment]
Your welcome :smile:. I am working on a new version that includes file upload enhancements for progress. As far as percentage goes, the value of the progress closure is between 0 and 1 (like NS/UI progressView), so if you times the progress value returned be 100 it will be the percentage of the progress.

**Comment by Mauricevb** [comment]
Very nice! Any idea when that update will be available? And I assume the upload still works for multipart form data :)?

**Comment by daltoniam** [comment]
It is available now in the master branch! It will indeed still work with multipart form data. I add an upload method for progress as that was not previously available. 
https://github.com/daltoniam/SwiftHTTP#upload

This is a fairly sizable refactor, so I will create the `0.9.5` tag after some more testing, but master should be ready to test out.

**Comment by Mauricevb** [comment]
Thank you so much! :)
