### ISSUE TITLE
Inconsistent consolidation of success and failure into single completion handler

### ISSUE THREAD

**Issue by pizthewiz** [daltoniam/SwiftHTTP#96]
Looks like the SSL pinning change brought a small API tweak that consolidated the `success` and `failure` handlers as `completionHandler` but in a few cases, the `failure` handler still exists.

This consolidation has been done in:
- [`GET`](https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L243)
- [`POST`](https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L256)
- [`PATCH`](https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L269)
- [`download`](https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L324)
- [`upload`](https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L353)

but not for:
- [`PUT`](https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L283)
- [`DELETE`](https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L296)
- [`HEAD`](https://github.com/daltoniam/SwiftHTTP/blob/master/HTTPTask.swift#L309)

Should the remaining three also use a single `completionHandler`?

**Comment by daltoniam** [comment]
Ah, good catch, they should also be remove. Thank you much. I just check in the remedy.
