### ISSUE TITLE
CocoaPod

### ISSUE THREAD

**Issue by gsiddharth** [daltoniam/SwiftHTTP#97]
Hey

First of all let me thank you for writing this library. I was wondering if you can please provide the latest version through CocoaPod. The current one is 0.9.4 which seems quite old.

Thanks
Regards
Siddharth Garg

**Comment by daltoniam** [comment]
Yeah it has been a while since a new Cocoapods version has been release. I have a `0.9.5` tag pending on what we hear back from #86 then will push a new version once that feature has been tested.
