### ISSUE TITLE
Uploading files in background

### ISSUE THREAD

**Issue by Mauricevb** [daltoniam/SwiftHTTP#98]
When i'm uploading a file and open another app, i get the error message: 

```
NSURLErrorDomain Code=-997 "Lost connection to background transfer service" UserInfo=0x174663c40 {NSErrorFailingURLStringKey=http://.......
```

I tried to find the problem, but I don't understand what's happening in all that lines of code.
Is it possible to continue uploading when the app is in the background? NSURLSession supports it.

**Edit:**
Maybe I found the problem in Apple's documentation: "Only upload and download tasks are supported (no data tasks)." (https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/UsingNSURLSession.html)

In the code I found: HTTPTask.swift (line 366):
```let task = session.dataTaskWithRequest(serialReq.request)```

Is it possible to use a upload task and still upload via multipart form data?

**Edit 2:**
Updated ```dataTaskWithRequest``` to ```uploadTaskWithRequest```. Now it works perfectly :)

HTTPTask.swift, ~ line 366

``` swift
//let task = session.dataTaskWithRequest(serialReq.request)  -- old line

// Search for an HTTPUpload object to upload
var keyForFile : String?
for (key, object) in parameters! {
	if object is HTTPUpload {
		keyForFile = key
		break
	}
}

// No HTTPUpload object given in parameters
if keyForFile != nil {
	// Upload task instead of data task. Upload HTTPUpload object.
	let task = session.uploadTaskWithRequest(serialReq.request, fromData: parameters![keyForFile!] as? NSData)

	self.backgroundTaskMap[ident] = BackgroundBlocks(completionHandler,progress)
	task.resume()
	return task
	
} else {
	// No HTTPUpload object found; nothing to upload
	return nil
}
```

**Comment by daltoniam** [comment]
Interesting, nice work. I originally made it a `uploadTaskWithRequest `, but hit an assertion that background upload tasks didn't support the `uploadTaskWithRequest:fromData:` version. The only drawback to this change is it will only support uploading one file in the background at a time (probably the most common case though). 

Also you are casting the `HTTPUpload` object into `NSData` and that is working properly for the upload? I would think you would need to pull the data out of the `HTTPUpload` object for it to work properly....

Anyway, nice work. That was just some thoughts I had seeing the changes, but I appreciate you taking the time to track this down. Let me know what you think and we can then improve with these changes.

**Comment by Mauricevb** [comment]
@daltoniam 
Indeed. You have to make a request for every single file unfortunately.

Casting the HTTPUpload directly to a NSData object is a oversight, but it seems to work on my NodeJS server. It did not work on my PHP server and I think this is why. I will test if it works when I grap the data out of the HTTPUpload object.

What do you think is the best way to implement this code change in the library?

**Comment by daltoniam** [comment]
Yeah that is strange that it accepts the HTTPUpload as NSData. That is the same assertion I got originally as well. I agree with the `fromFile:` task. I don't necessarily love the idea of have to write the file to disk only to read it back up right after. Guess it would be ok for files that where already on disk, but I think losing all the other parameters is a big issue imho. I find the background upload APIs for NSURLSession somewhat limited, but alas we work with what we have :confused:. The only other route we might be able to go is to use the `uploadTaskWithStreamedRequest:`, but not exactly sure how that would look like implemented or if it would do what we want.

**Comment by Mauricevb** [comment]
Tried ```uploadTaskWithStreamedRequest()``` and this works perfectly! 
So the only line that must be modified in order to support background uploads is:
``` swift
let task = session.dataTaskWithRequest(serialReq.request)
```
to
``` swift
let task = session.uploadTaskWithStreamedRequest(serialReq.request)
```
(Line ~266 in HTTPTask.swift)

All other code in this issue is no longer needed :)

**Comment by daltoniam** [comment]
Sweetness, glad it is that simple. I am curious if or when it might call `URLSession:task:needNewBodyStream` and if not implemented what it will do. Seems to work ok in my testing too, so we will run with it and hope it is that simple :smile:. Thanks for the help! 

476eaec04bbb3f13ed1e7e51bf2c5cd4685e7e68

**Comment by xingjizhao** [comment]
i have the same problem, and uploadTaskWithStreamedRequest does't help, any ideas?
