### ISSUE TITLE
Bring back success and failure

### ISSUE THREAD

**Issue by LeoUnglaub** [daltoniam/SwiftHTTP#99]
Hey,
i notices that you changes the function signature of `.POST`, `.GET`, ... to only only have `completionHandler` instead of two seperate params. In my opinion this makes it harder to write large apps because in my projects i have a global failure function that is always passed in as a reference from my base controller. I used to only specify the success function in my view controller.

Now i have to always check if its successfull and call the failure function manually. If you have 14 parts in your app that do HTTP requests, you have to write a lot of dublicated code.

Greetings
Leo

**Comment by daltoniam** [comment]
Hey Leo,
I thought this might be a more controversial change :smile:. I believe the `completionHandler` is a better setup for a few reasons. 

- It is more idiomatic Swift. Swift favors a single trailing closure on the methods and allows for a bit simpler code.
- It encourages handling the error case. It is simple to just ignore the `failure` closure and thus that code path. Using the single closure gives a single non optional `HTTPResponse` type and allows you to just check the error to see if the request failed, then handle the response object.
- Did I mention it cleaned up the syntax :smile: 

For the issue you mentioned with a global failure function, I think that might be able to be accomplished with something like so:

```swift
var request = HTTPTask()
request.GET("http://vluxe.io", parameters: nil, completionHandler: {(response: HTTPResponse) in
	if failureHandler(response) { //failureHandler is your global closure to handle failure processing
		//if failure handler returns true, all is good and do your success work
	}
})

//example global failure closure
func failureHandler(response: HTTPResponse) -> Bool {
	if let err = response.error {
        println("error: \(err.localizedDescription)")
        //.... show UI alert or whatever the default handling is
        return false //failed we got an error
    }
    return true
}
```

Any questions, let me know.

**Comment by LeoUnglaub** [comment]
Hmm, i still dont think it's a change for the better, i am going to run with it. Thanks for explaining anyway :)
